In [1]:
import pandas as pd
import plotly.express as px
import numpy as np

In [2]:
df = pd.read_csv("LengthOfStay.csv",index_col=0)
df.head()

,vdate,rcount,gender,dialysisrenalendstage,asthma,irondef,pneum,substancedependence,psychologicaldisordermajor,depress,...,glucose,bloodureanitro,creatinine,bmi,pulse,respiration,secondarydiagnosisnonicd9,discharged,facid,lengthofstay
eid,,,,,,,,,,,,,,,,,,,,,
1,8/29/2012,0,F,0,0,0,0,0,0,0,...,192.476918,12.0,1.390722,30.432418,96,6.5,4,9/1/2012,B,3
2,5/26/2012,5+,F,0,0,0,0,0,0,0,...,94.078507,8.0,0.943164,28.460516,61,6.5,1,6/2/2012,A,7
3,9/22/2012,1,F,0,0,0,0,0,0,0,...,130.530524,12.0,1.065750,28.843812,64,6.5,2,9/25/2012,B,3
4,8/9/2012,0,F,0,0,0,0,0,0,0,...,163.377028,12.0,0.906862,27.959007,76,6.5,1,8/10/2012,A,1
5,12/20/2012,0,F,0,0,0,1,0,1,0,...,94.886654,11.5,1.242854,30.258927,67,5.6,2,12/24/2012,E,4

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100000 entries, 1 to 100000
Data columns (total 27 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   vdate                       100000 non-null  object
 1   rcount                      100000 non-null  object
 2   gender                      100000 non-null  object
 3   dialysisrenalendstage       100000 non-null  int64
 4   asthma                      100000 non-null  int64
 5   irondef                     100000 non-null  int64
 6   pneum                       100000 non-null  int64
 7   substancedependence         100000 non-null  int64
 8   psychologicaldisordermajor  100000 non-null  int64
 9   depress                     100000 non-null  int64
 10  psychother                  100000 non-null  int64
 11  fibrosisandother            100000 non-null  int64
 12  malnutrition                100000 non-null  int64
 13  hemo                        100000 non-null  int64
 14  hematocrit                  100000 non-null  float64
 15  neutrophils                 100000 non-null  float64
 16  sodium                      100000 non-null  float64
 17  glucose                     100000 non-null  float64
 18  bloodureanitro              100000 non-null  float64
 19  creatinine                  100000 non-null  float64
 20  bmi                         100000 non-null  float64
 21  pulse                       100000 non-null  int64
 22  respiration                 100000 non-null  float64
 23  secondarydiagnosisnonicd9   100000 non-null  int64
 24  discharged                  100000 non-null  object
 25  facid                       100000 non-null  object
 26  lengthofstay                100000 non-null  int64
dtypes: float64(8), int64(14), object(5)
memory usage: 21.4+ MB

In [4]:
df.duplicated().sum()

np.int64(0)

In [5]:
df.drop_duplicates(inplace=True)

In [6]:
df.drop(columns=['vdate','discharged','facid','secondarydiagnosisnonicd9'], inplace=True)

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
x = df.drop(['lengthofstay'],axis=1)
y = df['lengthofstay']

In [9]:
num_cols = x.select_dtypes(include= 'number').columns
num_cols

Index(['dialysisrenalendstage', 'asthma', 'irondef', 'pneum',
       'substancedependence', 'psychologicaldisordermajor', 'depress',
       'psychother', 'fibrosisandother', 'malnutrition', 'hemo', 'hematocrit',
       'neutrophils', 'sodium', 'glucose', 'bloodureanitro', 'creatinine',
       'bmi', 'pulse', 'respiration'],
      dtype='object')

In [10]:
cat_cols = x.select_dtypes(include= 'object').columns
cat_cols

Index(['rcount', 'gender'], dtype='object')

In [11]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.pipeline import Pipeline

scaler = MinMaxScaler()

num_pipline = Pipeline(steps=[('Scaler',scaler)])
num_pipline

Pipeline(steps=[('Scaler', MinMaxScaler())])

In [12]:
from category_encoders import BinaryEncoder

BE = BinaryEncoder()

Cat_Pipeline = Pipeline(steps= [ ('Binary Encoder', BE) ])
Cat_Pipeline

Pipeline(steps=[('Binary Encoder', BinaryEncoder())])

In [13]:
from sklearn.compose import ColumnTransformer

preprocessing = ColumnTransformer(transformers= [ ('Num Pipeline', num_pipline, num_cols),
                                                  ('Cat Pipeline', Cat_Pipeline, cat_cols) ],
                                                  remainder= 'passthrough')
preprocessing

ColumnTransformer(remainder='passthrough',
                  transformers=[('Num Pipeline',
                                 Pipeline(steps=[('Scaler', MinMaxScaler())]),
                                 Index(['dialysisrenalendstage', 'asthma', 'irondef', 'pneum',
       'substancedependence', 'psychologicaldisordermajor', 'depress',
       'psychother', 'fibrosisandother', 'malnutrition', 'hemo', 'hematocrit',
       'neutrophils', 'sodium', 'glucose', 'bloodureanitro', 'creatinine',
       'bmi', 'pulse', 'respiration'],
      dtype='object')),
                                ('Cat Pipeline',
                                 Pipeline(steps=[('Binary Encoder',
                                                  BinaryEncoder())]),
                                 Index(['rcount', 'gender'], dtype='object'))])

In [14]:
from sklearn.linear_model import LinearRegression, Lasso, Ridge, ElasticNet
from sklearn.preprocessing import PolynomialFeatures
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from catboost import CatBoostRegressor
from lightgbm import LGBMRegressor
from sklearn.model_selection import cross_validate

models = [ ('Linear Regression', LinearRegression()),
           ('Lasso', Lasso(random_state = 42)),
           ('Ridge', Ridge(random_state= 42)),
           ('ElasticNet', ElasticNet(random_state= 42)),
           ('Polynomial', PolynomialFeatures(degree = 2)),
           ('Knn Regressor', KNeighborsRegressor(n_neighbors= 5)),
           #('SVM', SVR(kernel= 'linear')),
           ('DT', DecisionTreeRegressor(random_state = 42)),
           ('RF', RandomForestRegressor(random_state = 42, n_jobs= -1)),
           ('XGB', XGBRegressor(random_state = 42, n_jobs= -1)),
           ('CB', CatBoostRegressor(random_state = 42)),
           ('LGBM', LGBMRegressor(random_state = 42, n_jobs= -1)),
           ]

for model in models:

    model_pipeline = Pipeline(steps= [ ('Preprocessing', preprocessing), ('Model', model[1])])

    if model[0] == 'Polynomial':
        model_pipeline = Pipeline(steps= [ ('Preprocessing', preprocessing), ('Polynomial', model[1]), ('Model', Ridge(random_state= 42))])

    cv_results = cross_validate(estimator= model_pipeline, X= x, y= y, cv= 5, scoring= 'r2', return_train_score= True)

    print(model[0])
    print('Train R2 Score :', round(cv_results['train_score'].mean() * 100, 3))
    print('Test R2 Score :', round(cv_results['test_score'].mean() * 100, 3))
    print('Average Training Time :', round(cv_results['fit_time'].mean(), 4))
    print('-' * 50)

Linear Regression
Train R2 Score : 53.63
Test R2 Score : 53.621
Average Training Time : 0.308
--------------------------------------------------
Lasso
Train R2 Score : 0.0
Test R2 Score : -0.001
Average Training Time : 0.2405
--------------------------------------------------
Ridge
Train R2 Score : 53.63
Test R2 Score : 53.621
Average Training Time : 0.2522
--------------------------------------------------
ElasticNet
Train R2 Score : 1.3
Test R2 Score : 1.298
Average Training Time : 0.3655
--------------------------------------------------
Polynomial
Train R2 Score : 86.662
Test R2 Score : 86.456
Average Training Time : 0.7739
--------------------------------------------------
Knn Regressor
Train R2 Score : 89.0
Test R2 Score : 82.877
Average Training Time : 0.1529
--------------------------------------------------
DT
Train R2 Score : 100.0
Test R2 Score : 85.048
Average Training Time : 1.3691
--------------------------------------------------
RF
Train R2 Score : 98.952
Test R2 Score : 92.567
Average Training Time : 10.1691
--------------------------------------------------
XGB
Train R2 Score : 97.356
Test R2 Score : 96.296
Average Training Time : 0.4209
--------------------------------------------------
Learning rate set to 0.081822
0:	learn: 2.2264951	total: 154ms	remaining: 2m 34s
1:	learn: 2.1022487	total: 160ms	remaining: 1m 19s
2:	learn: 1.9907855	total: 164ms	remaining: 54.6s
3:	learn: 1.8921082	total: 170ms	remaining: 42.2s
4:	learn: 1.8028745	total: 174ms	remaining: 34.6s
5:	learn: 1.7232219	total: 178ms	remaining: 29.6s
6:	learn: 1.6530479	total: 184ms	remaining: 26.1s
7:	learn: 1.5892486	total: 189ms	remaining: 23.4s
8:	learn: 1.5331153	total: 194ms	remaining: 21.3s
9:	learn: 1.4819916	total: 200ms	remaining: 19.8s
10:	learn: 1.4386747	total: 205ms	remaining: 18.4s
11:	learn: 1.3980035	total: 210ms	remaining: 17.3s
12:	learn: 1.3624394	total: 215ms	remaining: 16.3s
13:	learn: 1.3296793	total: 219ms	remaining: 15.4s
14:	learn: 1.2996373	total: 223ms	remaining: 14.6s
15:	learn: 1.2738589	total: 228ms	remaining: 14s
16:	learn: 1.2491478	total: 234ms	remaining: 13.5s
17:	learn: 1.2258906	total: 239ms	remaining: 13s
18:	learn: 1.2054419	total: 245ms	remaining: 12.6s
19:	learn: 1.1853179	total: 251ms	remaining: 12.3s
20:	learn: 1.1638388	total: 256ms	remaining: 11.9s
21:	learn: 1.1442849	total: 261ms	remaining: 11.6s
22:	learn: 1.1257757	total: 265ms	remaining: 11.3s
23:	learn: 1.1074028	total: 270ms	remaining: 11s
24:	learn: 1.0895682	total: 275ms	remaining: 10.7s
25:	learn: 1.0734863	total: 279ms	remaining: 10.4s
26:	learn: 1.0569384	total: 283ms	remaining: 10.2s
27:	learn: 1.0404771	total: 288ms	remaining: 9.99s
28:	learn: 1.0255802	total: 293ms	remaining: 9.81s
29:	learn: 1.0111541	total: 299ms	remaining: 9.66s
30:	learn: 0.9959594	total: 304ms	remaining: 9.51s
31:	learn: 0.9824055	total: 309ms	remaining: 9.36s
32:	learn: 0.9676992	total: 315ms	remaining: 9.22s
33:	learn: 0.9547608	total: 321ms	remaining: 9.13s
34:	learn: 0.9423476	total: 327ms	remaining: 9s
35:	learn: 0.9297818	total: 333ms	remaining: 8.92s
36:	learn: 0.9183683	total: 338ms	remaining: 8.8s
37:	learn: 0.9070788	total: 343ms	remaining: 8.68s
38:	learn: 0.8955903	total: 347ms	remaining: 8.55s
39:	learn: 0.8848951	total: 352ms	remaining: 8.44s
40:	learn: 0.8747573	total: 356ms	remaining: 8.33s
41:	learn: 0.8643398	total: 361ms	remaining: 8.23s
42:	learn: 0.8526172	total: 366ms	remaining: 8.13s
43:	learn: 0.8431136	total: 369ms	remaining: 8.03s
44:	learn: 0.8337448	total: 374ms	remaining: 7.93s
45:	learn: 0.8249510	total: 378ms	remaining: 7.84s
46:	learn: 0.8158047	total: 383ms	remaining: 7.76s
47:	learn: 0.8053272	total: 390ms	remaining: 7.73s
48:	learn: 0.7967091	total: 395ms	remaining: 7.67s
49:	learn: 0.7868999	total: 401ms	remaining: 7.62s
50:	learn: 0.7788171	total: 406ms	remaining: 7.56s
51:	learn: 0.7716680	total: 410ms	remaining: 7.47s
52:	learn: 0.7644508	total: 415ms	remaining: 7.42s
53:	learn: 0.7555351	total: 420ms	remaining: 7.36s
54:	learn: 0.7480991	total: 424ms	remaining: 7.29s
55:	learn: 0.7395627	total: 428ms	remaining: 7.22s
56:	learn: 0.7333972	total: 434ms	remaining: 7.18s
57:	learn: 0.7261119	total: 439ms	remaining: 7.13s
58:	learn: 0.7201534	total: 444ms	remaining: 7.09s
59:	learn: 0.7131009	total: 449ms	remaining: 7.04s
60:	learn: 0.7048915	total: 454ms	remaining: 6.99s
61:	learn: 0.6988368	total: 459ms	remaining: 6.94s
62:	learn: 0.6937102	total: 464ms	remaining: 6.9s
63:	learn: 0.6885010	total: 468ms	remaining: 6.85s
64:	learn: 0.6820992	total: 474ms	remaining: 6.82s
65:	learn: 0.6767447	total: 479ms	remaining: 6.78s
66:	learn: 0.6715949	total: 485ms	remaining: 6.75s
67:	learn: 0.6647043	total: 491ms	remaining: 6.72s
68:	learn: 0.6605383	total: 496ms	remaining: 6.69s
69:	learn: 0.6553779	total: 500ms	remaining: 6.65s
70:	learn: 0.6507257	total: 504ms	remaining: 6.6s
71:	learn: 0.6457296	total: 509ms	remaining: 6.56s
72:	learn: 0.6413719	total: 514ms	remaining: 6.53s
73:	learn: 0.6373640	total: 518ms	remaining: 6.49s
74:	learn: 0.6336202	total: 523ms	remaining: 6.45s
75:	learn: 0.6278366	total: 528ms	remaining: 6.42s
76:	learn: 0.6243747	total: 533ms	remaining: 6.39s
77:	learn: 0.6193494	total: 539ms	remaining: 6.37s
78:	learn: 0.6159058	total: 543ms	remaining: 6.33s
79:	learn: 0.6125907	total: 548ms	remaining: 6.3s
80:	learn: 0.6083158	total: 553ms	remaining: 6.27s
81:	learn: 0.6043138	total: 557ms	remaining: 6.23s
82:	learn: 0.6008872	total: 561ms	remaining: 6.2s
83:	learn: 0.5977973	total: 565ms	remaining: 6.16s
84:	learn: 0.5950273	total: 569ms	remaining: 6.13s
85:	learn: 0.5908156	total: 574ms	remaining: 6.1s
86:	learn: 0.5866843	total: 579ms	remaining: 6.07s
87:	learn: 0.5835704	total: 583ms	remaining: 6.04s
88:	learn: 0.5799356	total: 588ms	remaining: 6.02s
89:	learn: 0.5770588	total: 594ms	remaining: 6s
90:	learn: 0.5741634	total: 600ms	remaining: 5.99s
91:	learn: 0.5708175	total: 604ms	remaining: 5.96s
92:	learn: 0.5680675	total: 609ms	remaining: 5.94s
93:	learn: 0.5656123	total: 614ms	remaining: 5.92s
94:	learn: 0.5633859	total: 618ms	remaining: 5.89s
95:	learn: 0.5613894	total: 624ms	remaining: 5.88s
96:	learn: 0.5587294	total: 630ms	remaining: 5.87s
97:	learn: 0.5563881	total: 636ms	remaining: 5.86s
98:	learn: 0.5527307	total: 641ms	remaining: 5.84s
99:	learn: 0.5501441	total: 646ms	remaining: 5.82s
100:	learn: 0.5480969	total: 651ms	remaining: 5.79s
101:	learn: 0.5459631	total: 655ms	remaining: 5.77s
102:	learn: 0.5442523	total: 659ms	remaining: 5.74s
103:	learn: 0.5415766	total: 664ms	remaining: 5.72s
104:	learn: 0.5396118	total: 668ms	remaining: 5.7s
105:	learn: 0.5375808	total: 673ms	remaining: 5.67s
106:	learn: 0.5359290	total: 677ms	remaining: 5.65s
107:	learn: 0.5336208	total: 683ms	remaining: 5.64s
108:	learn: 0.5322523	total: 688ms	remaining: 5.62s
109:	learn: 0.5304786	total: 693ms	remaining: 5.61s
110:	learn: 0.5289544	total: 697ms	remaining: 5.58s
111:	learn: 0.5259176	total: 702ms	remaining: 5.57s
112:	learn: 0.5245216	total: 707ms	remaining: 5.55s
113:	learn: 0.5232356	total: 712ms	remaining: 5.53s
114:	learn: 0.5215191	total: 717ms	remaining: 5.52s
115:	learn: 0.5195292	total: 724ms	remaining: 5.51s
116:	learn: 0.5179934	total: 729ms	remaining: 5.5s
117:	learn: 0.5159507	total: 734ms	remaining: 5.48s
118:	learn: 0.5147388	total: 738ms	remaining: 5.46s
119:	learn: 0.5136375	total: 742ms	remaining: 5.44s
120:	learn: 0.5122045	total: 747ms	remaining: 5.43s
121:	learn: 0.5107722	total: 751ms	remaining: 5.41s
122:	learn: 0.5090011	total: 755ms	remaining: 5.38s
123:	learn: 0.5063109	total: 759ms	remaining: 5.36s
124:	learn: 0.5052387	total: 764ms	remaining: 5.34s
125:	learn: 0.5038800	total: 770ms	remaining: 5.34s
126:	learn: 0.5024667	total: 775ms	remaining: 5.33s
127:	learn: 0.5007898	total: 781ms	remaining: 5.32s
128:	learn: 0.4993205	total: 786ms	remaining: 5.31s
129:	learn: 0.4973283	total: 791ms	remaining: 5.29s
130:	learn: 0.4961469	total: 796ms	remaining: 5.28s
131:	learn: 0.4947971	total: 802ms	remaining: 5.27s
132:	learn: 0.4937180	total: 807ms	remaining: 5.26s
133:	learn: 0.4926986	total: 812ms	remaining: 5.25s
134:	learn: 0.4917243	total: 818ms	remaining: 5.24s
135:	learn: 0.4906995	total: 822ms	remaining: 5.22s
136:	learn: 0.4892225	total: 827ms	remaining: 5.21s
137:	learn: 0.4880161	total: 831ms	remaining: 5.19s
138:	learn: 0.4864761	total: 836ms	remaining: 5.18s
139:	learn: 0.4855326	total: 841ms	remaining: 5.17s
140:	learn: 0.4845826	total: 846ms	remaining: 5.15s
141:	learn: 0.4834160	total: 850ms	remaining: 5.14s
142:	learn: 0.4824695	total: 854ms	remaining: 5.12s
143:	learn: 0.4815983	total: 859ms	remaining: 5.11s
144:	learn: 0.4803560	total: 864ms	remaining: 5.1s
145:	learn: 0.4795513	total: 869ms	remaining: 5.08s
146:	learn: 0.4785197	total: 875ms	remaining: 5.08s
147:	learn: 0.4775117	total: 879ms	remaining: 5.06s
148:	learn: 0.4766167	total: 884ms	remaining: 5.05s
149:	learn: 0.4757002	total: 888ms	remaining: 5.03s
150:	learn: 0.4749120	total: 892ms	remaining: 5.01s
151:	learn: 0.4734931	total: 896ms	remaining: 5s
152:	learn: 0.4724018	total: 902ms	remaining: 4.99s
153:	learn: 0.4715095	total: 906ms	remaining: 4.98s
154:	learn: 0.4705949	total: 912ms	remaining: 4.97s
155:	learn: 0.4697593	total: 917ms	remaining: 4.96s
156:	learn: 0.4687772	total: 922ms	remaining: 4.95s
157:	learn: 0.4679490	total: 927ms	remaining: 4.94s
158:	learn: 0.4664410	total: 932ms	remaining: 4.93s
159:	learn: 0.4656791	total: 937ms	remaining: 4.92s
160:	learn: 0.4648227	total: 941ms	remaining: 4.9s
161:	learn: 0.4641755	total: 946ms	remaining: 4.89s
162:	learn: 0.4628632	total: 950ms	remaining: 4.88s
163:	learn: 0.4620234	total: 954ms	remaining: 4.87s
164:	learn: 0.4613094	total: 961ms	remaining: 4.86s
165:	learn: 0.4605763	total: 966ms	remaining: 4.86s
166:	learn: 0.4594651	total: 971ms	remaining: 4.84s
167:	learn: 0.4589089	total: 977ms	remaining: 4.84s
168:	learn: 0.4578073	total: 982ms	remaining: 4.83s
169:	learn: 0.4570663	total: 988ms	remaining: 4.82s
170:	learn: 0.4563551	total: 993ms	remaining: 4.81s
171:	learn: 0.4557393	total: 997ms	remaining: 4.8s
172:	learn: 0.4550885	total: 1s	remaining: 4.79s
173:	learn: 0.4543638	total: 1.01s	remaining: 4.78s
174:	learn: 0.4537168	total: 1.01s	remaining: 4.78s
175:	learn: 0.4524760	total: 1.02s	remaining: 4.78s
176:	learn: 0.4513005	total: 1.02s	remaining: 4.76s
177:	learn: 0.4504571	total: 1.03s	remaining: 4.75s
178:	learn: 0.4498139	total: 1.03s	remaining: 4.74s
179:	learn: 0.4492847	total: 1.04s	remaining: 4.73s
180:	learn: 0.4484614	total: 1.04s	remaining: 4.72s
181:	learn: 0.4478186	total: 1.05s	remaining: 4.71s
182:	learn: 0.4473523	total: 1.05s	remaining: 4.7s
183:	learn: 0.4468407	total: 1.06s	remaining: 4.69s
184:	learn: 0.4459732	total: 1.06s	remaining: 4.68s
185:	learn: 0.4454623	total: 1.07s	remaining: 4.68s
186:	learn: 0.4450040	total: 1.07s	remaining: 4.67s
187:	learn: 0.4444337	total: 1.08s	remaining: 4.66s
188:	learn: 0.4438764	total: 1.08s	remaining: 4.65s
189:	learn: 0.4432425	total: 1.09s	remaining: 4.64s
190:	learn: 0.4424059	total: 1.09s	remaining: 4.64s
191:	learn: 0.4417234	total: 1.1s	remaining: 4.63s
192:	learn: 0.4412638	total: 1.1s	remaining: 4.62s
193:	learn: 0.4407496	total: 1.11s	remaining: 4.62s
194:	learn: 0.4400768	total: 1.12s	remaining: 4.61s
195:	learn: 0.4394766	total: 1.12s	remaining: 4.6s
196:	learn: 0.4389328	total: 1.13s	remaining: 4.59s
197:	learn: 0.4385629	total: 1.13s	remaining: 4.58s
198:	learn: 0.4372093	total: 1.13s	remaining: 4.57s
199:	learn: 0.4367918	total: 1.14s	remaining: 4.55s
200:	learn: 0.4363896	total: 1.14s	remaining: 4.55s
201:	learn: 0.4358925	total: 1.15s	remaining: 4.54s
202:	learn: 0.4352119	total: 1.15s	remaining: 4.53s
203:	learn: 0.4346989	total: 1.16s	remaining: 4.52s
204:	learn: 0.4342936	total: 1.17s	remaining: 4.52s
205:	learn: 0.4337168	total: 1.17s	remaining: 4.51s
206:	learn: 0.4332768	total: 1.17s	remaining: 4.5s
207:	learn: 0.4327658	total: 1.18s	remaining: 4.49s
208:	learn: 0.4320388	total: 1.18s	remaining: 4.48s
209:	learn: 0.4317346	total: 1.19s	remaining: 4.47s
210:	learn: 0.4313920	total: 1.19s	remaining: 4.46s
211:	learn: 0.4310725	total: 1.2s	remaining: 4.45s
212:	learn: 0.4303882	total: 1.2s	remaining: 4.44s
213:	learn: 0.4299209	total: 1.21s	remaining: 4.44s
214:	learn: 0.4295368	total: 1.21s	remaining: 4.43s
215:	learn: 0.4290051	total: 1.22s	remaining: 4.42s
216:	learn: 0.4285424	total: 1.22s	remaining: 4.42s
217:	learn: 0.4282961	total: 1.23s	remaining: 4.41s
218:	learn: 0.4279742	total: 1.23s	remaining: 4.4s
219:	learn: 0.4274497	total: 1.24s	remaining: 4.39s
220:	learn: 0.4270829	total: 1.24s	remaining: 4.38s
221:	learn: 0.4266569	total: 1.25s	remaining: 4.37s
222:	learn: 0.4261497	total: 1.25s	remaining: 4.37s
223:	learn: 0.4258589	total: 1.26s	remaining: 4.36s
224:	learn: 0.4254753	total: 1.26s	remaining: 4.36s
225:	learn: 0.4252122	total: 1.27s	remaining: 4.35s
226:	learn: 0.4248010	total: 1.27s	remaining: 4.34s
227:	learn: 0.4243790	total: 1.28s	remaining: 4.33s
228:	learn: 0.4239355	total: 1.28s	remaining: 4.33s
229:	learn: 0.4237136	total: 1.29s	remaining: 4.32s
230:	learn: 0.4227315	total: 1.29s	remaining: 4.31s
231:	learn: 0.4223984	total: 1.3s	remaining: 4.3s
232:	learn: 0.4221369	total: 1.3s	remaining: 4.3s
233:	learn: 0.4218831	total: 1.31s	remaining: 4.29s
234:	learn: 0.4215836	total: 1.31s	remaining: 4.28s
235:	learn: 0.4213892	total: 1.32s	remaining: 4.27s
236:	learn: 0.4209351	total: 1.32s	remaining: 4.26s
237:	learn: 0.4207001	total: 1.33s	remaining: 4.25s
238:	learn: 0.4203832	total: 1.33s	remaining: 4.25s
239:	learn: 0.4200741	total: 1.34s	remaining: 4.24s
240:	learn: 0.4198103	total: 1.34s	remaining: 4.23s
241:	learn: 0.4193385	total: 1.35s	remaining: 4.22s
242:	learn: 0.4190177	total: 1.35s	remaining: 4.21s
243:	learn: 0.4187271	total: 1.36s	remaining: 4.21s
244:	learn: 0.4184613	total: 1.36s	remaining: 4.2s
245:	learn: 0.4176398	total: 1.37s	remaining: 4.19s
246:	learn: 0.4173902	total: 1.37s	remaining: 4.18s
247:	learn: 0.4169829	total: 1.38s	remaining: 4.17s
248:	learn: 0.4165072	total: 1.38s	remaining: 4.16s
249:	learn: 0.4162063	total: 1.38s	remaining: 4.15s
250:	learn: 0.4159581	total: 1.39s	remaining: 4.14s
251:	learn: 0.4156803	total: 1.39s	remaining: 4.14s
252:	learn: 0.4154297	total: 1.4s	remaining: 4.13s
253:	learn: 0.4151883	total: 1.4s	remaining: 4.12s
254:	learn: 0.4149093	total: 1.41s	remaining: 4.11s
255:	learn: 0.4144498	total: 1.41s	remaining: 4.11s
256:	learn: 0.4142510	total: 1.42s	remaining: 4.1s
257:	learn: 0.4139585	total: 1.42s	remaining: 4.09s
258:	learn: 0.4136699	total: 1.43s	remaining: 4.08s
259:	learn: 0.4135074	total: 1.43s	remaining: 4.08s
260:	learn: 0.4133093	total: 1.44s	remaining: 4.07s
261:	learn: 0.4130697	total: 1.44s	remaining: 4.06s
262:	learn: 0.4126816	total: 1.45s	remaining: 4.06s
263:	learn: 0.4124427	total: 1.45s	remaining: 4.05s
264:	learn: 0.4117459	total: 1.46s	remaining: 4.04s
265:	learn: 0.4114251	total: 1.46s	remaining: 4.03s
266:	learn: 0.4111287	total: 1.46s	remaining: 4.02s
267:	learn: 0.4109295	total: 1.47s	remaining: 4.01s
268:	learn: 0.4107621	total: 1.47s	remaining: 4.01s
269:	learn: 0.4105075	total: 1.48s	remaining: 4s
270:	learn: 0.4098349	total: 1.49s	remaining: 4s
271:	learn: 0.4095941	total: 1.49s	remaining: 4s
272:	learn: 0.4094649	total: 1.5s	remaining: 3.99s
273:	learn: 0.4092801	total: 1.5s	remaining: 3.98s
274:	learn: 0.4091292	total: 1.51s	remaining: 3.97s
275:	learn: 0.4089609	total: 1.51s	remaining: 3.96s
276:	learn: 0.4088233	total: 1.51s	remaining: 3.95s
277:	learn: 0.4086278	total: 1.52s	remaining: 3.94s
278:	learn: 0.4080930	total: 1.52s	remaining: 3.94s
279:	learn: 0.4075106	total: 1.53s	remaining: 3.93s
280:	learn: 0.4073045	total: 1.53s	remaining: 3.93s
281:	learn: 0.4070720	total: 1.54s	remaining: 3.92s
282:	learn: 0.4067153	total: 1.55s	remaining: 3.92s
283:	learn: 0.4064732	total: 1.56s	remaining: 3.92s
284:	learn: 0.4063123	total: 1.56s	remaining: 3.92s
285:	learn: 0.4061607	total: 1.57s	remaining: 3.91s
286:	learn: 0.4059455	total: 1.57s	remaining: 3.91s
287:	learn: 0.4057978	total: 1.58s	remaining: 3.9s
288:	learn: 0.4052555	total: 1.58s	remaining: 3.9s
289:	learn: 0.4049589	total: 1.59s	remaining: 3.89s
290:	learn: 0.4046900	total: 1.59s	remaining: 3.88s
291:	learn: 0.4044800	total: 1.6s	remaining: 3.87s
292:	learn: 0.4041393	total: 1.6s	remaining: 3.87s
293:	learn: 0.4038904	total: 1.61s	remaining: 3.86s
294:	learn: 0.4037870	total: 1.61s	remaining: 3.85s
295:	learn: 0.4036299	total: 1.61s	remaining: 3.84s
296:	learn: 0.4034020	total: 1.62s	remaining: 3.83s
297:	learn: 0.4032566	total: 1.62s	remaining: 3.83s
298:	learn: 0.4030766	total: 1.63s	remaining: 3.82s
299:	learn: 0.4030124	total: 1.64s	remaining: 3.82s
300:	learn: 0.4027895	total: 1.64s	remaining: 3.81s
301:	learn: 0.4025683	total: 1.65s	remaining: 3.81s
302:	learn: 0.4024423	total: 1.65s	remaining: 3.8s
303:	learn: 0.4022400	total: 1.66s	remaining: 3.79s
304:	learn: 0.4020421	total: 1.66s	remaining: 3.78s
305:	learn: 0.4019008	total: 1.67s	remaining: 3.78s
306:	learn: 0.4016690	total: 1.67s	remaining: 3.77s
307:	learn: 0.4011597	total: 1.68s	remaining: 3.76s
308:	learn: 0.4010112	total: 1.68s	remaining: 3.76s
309:	learn: 0.4008901	total: 1.69s	remaining: 3.75s
310:	learn: 0.4007268	total: 1.69s	remaining: 3.74s
311:	learn: 0.4006206	total: 1.69s	remaining: 3.73s
312:	learn: 0.4004800	total: 1.7s	remaining: 3.73s
313:	learn: 0.4002830	total: 1.7s	remaining: 3.72s
314:	learn: 0.4001651	total: 1.71s	remaining: 3.71s
315:	learn: 0.4000178	total: 1.71s	remaining: 3.7s
316:	learn: 0.3998178	total: 1.72s	remaining: 3.69s
317:	learn: 0.3996384	total: 1.72s	remaining: 3.69s
318:	learn: 0.3995723	total: 1.73s	remaining: 3.68s
319:	learn: 0.3993818	total: 1.73s	remaining: 3.67s
320:	learn: 0.3992747	total: 1.73s	remaining: 3.67s
321:	learn: 0.3989574	total: 1.74s	remaining: 3.66s
322:	learn: 0.3986725	total: 1.74s	remaining: 3.65s
323:	learn: 0.3985424	total: 1.75s	remaining: 3.64s
324:	learn: 0.3982477	total: 1.75s	remaining: 3.64s
325:	learn: 0.3981753	total: 1.75s	remaining: 3.63s
326:	learn: 0.3979696	total: 1.76s	remaining: 3.62s
327:	learn: 0.3979081	total: 1.76s	remaining: 3.61s
328:	learn: 0.3977383	total: 1.77s	remaining: 3.61s
329:	learn: 0.3975801	total: 1.77s	remaining: 3.6s
330:	learn: 0.3974402	total: 1.78s	remaining: 3.59s
331:	learn: 0.3973600	total: 1.78s	remaining: 3.59s
332:	learn: 0.3972239	total: 1.79s	remaining: 3.58s
333:	learn: 0.3970960	total: 1.79s	remaining: 3.57s
334:	learn: 0.3969601	total: 1.8s	remaining: 3.57s
335:	learn: 0.3968559	total: 1.8s	remaining: 3.56s
336:	learn: 0.3966727	total: 1.8s	remaining: 3.55s
337:	learn: 0.3965103	total: 1.81s	remaining: 3.54s
338:	learn: 0.3963564	total: 1.81s	remaining: 3.54s
339:	learn: 0.3961950	total: 1.82s	remaining: 3.53s
340:	learn: 0.3960012	total: 1.82s	remaining: 3.52s
341:	learn: 0.3957827	total: 1.83s	remaining: 3.52s
342:	learn: 0.3956327	total: 1.84s	remaining: 3.52s
343:	learn: 0.3954092	total: 1.84s	remaining: 3.51s
344:	learn: 0.3952782	total: 1.84s	remaining: 3.5s
345:	learn: 0.3952268	total: 1.85s	remaining: 3.5s
346:	learn: 0.3950207	total: 1.85s	remaining: 3.49s
347:	learn: 0.3949045	total: 1.86s	remaining: 3.49s
348:	learn: 0.3948100	total: 1.86s	remaining: 3.48s
349:	learn: 0.3946752	total: 1.87s	remaining: 3.48s
350:	learn: 0.3945596	total: 1.88s	remaining: 3.48s
351:	learn: 0.3944286	total: 1.89s	remaining: 3.47s
352:	learn: 0.3943773	total: 1.89s	remaining: 3.46s
353:	learn: 0.3942468	total: 1.9s	remaining: 3.46s
354:	learn: 0.3941761	total: 1.9s	remaining: 3.45s
355:	learn: 0.3940302	total: 1.91s	remaining: 3.45s
356:	learn: 0.3939234	total: 1.91s	remaining: 3.44s
357:	learn: 0.3938598	total: 1.92s	remaining: 3.44s
358:	learn: 0.3937664	total: 1.92s	remaining: 3.43s
359:	learn: 0.3936813	total: 1.93s	remaining: 3.42s
360:	learn: 0.3936049	total: 1.93s	remaining: 3.42s
361:	learn: 0.3935717	total: 1.94s	remaining: 3.41s
362:	learn: 0.3934377	total: 1.94s	remaining: 3.41s

c:\MyAnaconda\envs\oop\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\MyAnaconda\envs\oop\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.008755 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1912
[LightGBM] [Info] Number of data points in the train set: 80000, number of used features: 25
[LightGBM] [Info] Start training from score 4.002987

c:\MyAnaconda\envs\oop\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\MyAnaconda\envs\oop\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002884 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1919
[LightGBM] [Info] Number of data points in the train set: 80000, number of used features: 25
[LightGBM] [Info] Start training from score 3.998838

c:\MyAnaconda\envs\oop\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\MyAnaconda\envs\oop\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.008390 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1919
[LightGBM] [Info] Number of data points in the train set: 80000, number of used features: 25
[LightGBM] [Info] Start training from score 3.999975

c:\MyAnaconda\envs\oop\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\MyAnaconda\envs\oop\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002722 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1971
[LightGBM] [Info] Number of data points in the train set: 80000, number of used features: 25
[LightGBM] [Info] Start training from score 4.001462
LGBM
Train R2 Score : 96.419
Test R2 Score : 96.057
Average Training Time : 0.4199
--------------------------------------------------

c:\MyAnaconda\envs\oop\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\MyAnaconda\envs\oop\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

In [15]:
catboost_pipeline = Pipeline(steps= [ ('Preprocessing', preprocessing), ('Model', CatBoostRegressor(random_state = 42))])
catboost_pipeline

Pipeline(steps=[('Preprocessing',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('Num Pipeline',
                                                  Pipeline(steps=[('Scaler',
                                                                   MinMaxScaler())]),
                                                  Index(['dialysisrenalendstage', 'asthma', 'irondef', 'pneum',
       'substancedependence', 'psychologicaldisordermajor', 'depress',
       'psychother', 'fibrosisandother', 'malnutrition', 'hemo', 'hematocrit',
       'neutrophils', 'sodium', 'glucose', 'bloodureanitro', 'creatinine',
       'bmi', 'pulse', 'respiration'],
      dtype='object')),
                                                 ('Cat Pipeline',
                                                  Pipeline(steps=[('Binary '
                                                                   'Encoder',
                                                                   BinaryEncoder())]),
                                                  Index(['rcount', 'gender'], dtype='object'))])),
                ('Model',
                 CatBoostRegressor(loss_function='RMSE', random_state=42))])

In [17]:
from sklearn.model_selection import RandomizedSearchCV

param_grid = {
    'Model__depth': [4, 6, 8],
    'Model__learning_rate': [0.01, 0.03, 0.05],
    'Model__iterations': [500, 800, 1200]
    }

# Turn off parallel processing entirely
random_search = RandomizedSearchCV(
    catboost_pipeline, 
    param_distributions=param_grid, 
    cv=5, 
    scoring='r2', 
    random_state=42, 
    return_train_score=True, 
    n_jobs=1  # Sequential processing
)

random_search.fit(x, y)

0:	learn: 2.2869234	total: 15.1ms	remaining: 18.1s
1:	learn: 2.2159264	total: 19.6ms	remaining: 11.7s
2:	learn: 2.1498330	total: 24ms	remaining: 9.59s
3:	learn: 2.0883826	total: 27.8ms	remaining: 8.31s
4:	learn: 2.0313224	total: 31.4ms	remaining: 7.5s
5:	learn: 1.9784080	total: 34.4ms	remaining: 6.84s
6:	learn: 1.9294022	total: 38.2ms	remaining: 6.51s
7:	learn: 1.8837511	total: 41.8ms	remaining: 6.23s
8:	learn: 1.8410537	total: 46ms	remaining: 6.08s
9:	learn: 1.8022495	total: 49.3ms	remaining: 5.86s
10:	learn: 1.7654120	total: 53.3ms	remaining: 5.76s
11:	learn: 1.7309921	total: 56.9ms	remaining: 5.63s
12:	learn: 1.6997182	total: 60.1ms	remaining: 5.48s
13:	learn: 1.6690778	total: 63.2ms	remaining: 5.35s
14:	learn: 1.6404230	total: 67ms	remaining: 5.29s
15:	learn: 1.6146763	total: 70ms	remaining: 5.18s
16:	learn: 1.5909125	total: 74ms	remaining: 5.15s
17:	learn: 1.5672564	total: 77.1ms	remaining: 5.06s
18:	learn: 1.5456073	total: 80.5ms	remaining: 5s
19:	learn: 1.5253749	total: 83.8ms	remaining: 4.95s
20:	learn: 1.5047761	total: 87.4ms	remaining: 4.91s
21:	learn: 1.4870873	total: 90.8ms	remaining: 4.86s
22:	learn: 1.4697180	total: 94ms	remaining: 4.81s
23:	learn: 1.4535550	total: 98.8ms	remaining: 4.84s
24:	learn: 1.4380625	total: 103ms	remaining: 4.83s
25:	learn: 1.4211639	total: 107ms	remaining: 4.83s
26:	learn: 1.4074444	total: 111ms	remaining: 4.83s
27:	learn: 1.3939941	total: 117ms	remaining: 4.88s
28:	learn: 1.3816527	total: 122ms	remaining: 4.91s
29:	learn: 1.3697029	total: 126ms	remaining: 4.9s
30:	learn: 1.3587092	total: 129ms	remaining: 4.87s
31:	learn: 1.3479439	total: 133ms	remaining: 4.84s
32:	learn: 1.3374378	total: 137ms	remaining: 4.84s
33:	learn: 1.3281793	total: 141ms	remaining: 4.84s
34:	learn: 1.3152322	total: 145ms	remaining: 4.84s
35:	learn: 1.3051810	total: 149ms	remaining: 4.82s
36:	learn: 1.2961775	total: 153ms	remaining: 4.81s
37:	learn: 1.2873739	total: 156ms	remaining: 4.77s
38:	learn: 1.2784286	total: 159ms	remaining: 4.75s
39:	learn: 1.2696319	total: 164ms	remaining: 4.74s
40:	learn: 1.2606010	total: 167ms	remaining: 4.72s
41:	learn: 1.2518276	total: 171ms	remaining: 4.71s
42:	learn: 1.2440084	total: 174ms	remaining: 4.69s
43:	learn: 1.2361739	total: 178ms	remaining: 4.67s
44:	learn: 1.2283062	total: 182ms	remaining: 4.67s
45:	learn: 1.2208327	total: 186ms	remaining: 4.67s
46:	learn: 1.2128990	total: 190ms	remaining: 4.66s
47:	learn: 1.2056462	total: 193ms	remaining: 4.64s
48:	learn: 1.1977746	total: 197ms	remaining: 4.63s
49:	learn: 1.1903627	total: 201ms	remaining: 4.63s
50:	learn: 1.1793783	total: 206ms	remaining: 4.64s
51:	learn: 1.1725376	total: 210ms	remaining: 4.63s
52:	learn: 1.1655651	total: 214ms	remaining: 4.63s
53:	learn: 1.1585847	total: 219ms	remaining: 4.64s
54:	learn: 1.1519704	total: 222ms	remaining: 4.62s
55:	learn: 1.1417632	total: 226ms	remaining: 4.62s
56:	learn: 1.1350042	total: 231ms	remaining: 4.63s
57:	learn: 1.1285553	total: 236ms	remaining: 4.64s
58:	learn: 1.1217941	total: 240ms	remaining: 4.64s
59:	learn: 1.1153986	total: 246ms	remaining: 4.67s
60:	learn: 1.1093938	total: 250ms	remaining: 4.67s
61:	learn: 1.1027212	total: 254ms	remaining: 4.67s
62:	learn: 1.0965724	total: 259ms	remaining: 4.68s
63:	learn: 1.0901324	total: 263ms	remaining: 4.67s
64:	learn: 1.0841010	total: 268ms	remaining: 4.68s
65:	learn: 1.0780373	total: 273ms	remaining: 4.69s
66:	learn: 1.0720089	total: 277ms	remaining: 4.68s
67:	learn: 1.0662247	total: 280ms	remaining: 4.67s
68:	learn: 1.0607501	total: 284ms	remaining: 4.66s
69:	learn: 1.0551346	total: 288ms	remaining: 4.66s
70:	learn: 1.0496393	total: 293ms	remaining: 4.66s
71:	learn: 1.0438376	total: 299ms	remaining: 4.68s
72:	learn: 1.0386820	total: 303ms	remaining: 4.68s
73:	learn: 1.0328645	total: 307ms	remaining: 4.68s
74:	learn: 1.0272324	total: 312ms	remaining: 4.68s
75:	learn: 1.0218562	total: 315ms	remaining: 4.66s
76:	learn: 1.0168096	total: 319ms	remaining: 4.65s
77:	learn: 1.0116510	total: 322ms	remaining: 4.63s
78:	learn: 1.0064584	total: 326ms	remaining: 4.63s
79:	learn: 1.0018868	total: 331ms	remaining: 4.63s
80:	learn: 0.9966246	total: 334ms	remaining: 4.61s
81:	learn: 0.9916716	total: 338ms	remaining: 4.61s
82:	learn: 0.9822205	total: 341ms	remaining: 4.59s
83:	learn: 0.9778357	total: 345ms	remaining: 4.58s
84:	learn: 0.9731443	total: 349ms	remaining: 4.57s
85:	learn: 0.9682421	total: 353ms	remaining: 4.58s
86:	learn: 0.9634851	total: 357ms	remaining: 4.57s
87:	learn: 0.9592568	total: 361ms	remaining: 4.56s
88:	learn: 0.9547354	total: 365ms	remaining: 4.55s
89:	learn: 0.9499320	total: 368ms	remaining: 4.54s
90:	learn: 0.9456896	total: 372ms	remaining: 4.53s
91:	learn: 0.9414515	total: 375ms	remaining: 4.52s
92:	learn: 0.9374829	total: 379ms	remaining: 4.51s
93:	learn: 0.9330198	total: 383ms	remaining: 4.5s
94:	learn: 0.9292185	total: 387ms	remaining: 4.5s
95:	learn: 0.9250767	total: 392ms	remaining: 4.5s
96:	learn: 0.9208753	total: 395ms	remaining: 4.49s
97:	learn: 0.9169351	total: 399ms	remaining: 4.49s
98:	learn: 0.9131949	total: 404ms	remaining: 4.49s
99:	learn: 0.9094892	total: 408ms	remaining: 4.48s
100:	learn: 0.9060994	total: 411ms	remaining: 4.47s
101:	learn: 0.9026684	total: 415ms	remaining: 4.47s
102:	learn: 0.8990671	total: 420ms	remaining: 4.47s
103:	learn: 0.8956295	total: 424ms	remaining: 4.47s
104:	learn: 0.8925166	total: 428ms	remaining: 4.46s
105:	learn: 0.8839622	total: 433ms	remaining: 4.47s
106:	learn: 0.8797177	total: 437ms	remaining: 4.46s
107:	learn: 0.8760032	total: 443ms	remaining: 4.48s
108:	learn: 0.8721964	total: 448ms	remaining: 4.48s
109:	learn: 0.8687375	total: 451ms	remaining: 4.47s
110:	learn: 0.8657032	total: 456ms	remaining: 4.48s
111:	learn: 0.8618374	total: 462ms	remaining: 4.49s
112:	learn: 0.8584282	total: 466ms	remaining: 4.48s
113:	learn: 0.8552552	total: 470ms	remaining: 4.47s
114:	learn: 0.8522980	total: 473ms	remaining: 4.46s
115:	learn: 0.8490442	total: 477ms	remaining: 4.45s
116:	learn: 0.8413034	total: 480ms	remaining: 4.44s
117:	learn: 0.8383683	total: 483ms	remaining: 4.43s
118:	learn: 0.8349641	total: 486ms	remaining: 4.42s
119:	learn: 0.8320092	total: 490ms	remaining: 4.41s
120:	learn: 0.8248722	total: 495ms	remaining: 4.41s
121:	learn: 0.8182680	total: 498ms	remaining: 4.4s
122:	learn: 0.8155350	total: 502ms	remaining: 4.4s
123:	learn: 0.8127666	total: 506ms	remaining: 4.39s
124:	learn: 0.8099687	total: 509ms	remaining: 4.38s
125:	learn: 0.8073496	total: 513ms	remaining: 4.37s
126:	learn: 0.8046498	total: 517ms	remaining: 4.37s
127:	learn: 0.8018697	total: 521ms	remaining: 4.36s
128:	learn: 0.7992670	total: 524ms	remaining: 4.35s
129:	learn: 0.7963816	total: 529ms	remaining: 4.35s
130:	learn: 0.7940143	total: 532ms	remaining: 4.34s
131:	learn: 0.7915605	total: 537ms	remaining: 4.34s
132:	learn: 0.7891389	total: 541ms	remaining: 4.34s
133:	learn: 0.7867096	total: 544ms	remaining: 4.33s
134:	learn: 0.7842694	total: 549ms	remaining: 4.33s
135:	learn: 0.7819774	total: 554ms	remaining: 4.33s
136:	learn: 0.7758225	total: 560ms	remaining: 4.34s
137:	learn: 0.7737413	total: 564ms	remaining: 4.34s
138:	learn: 0.7708504	total: 569ms	remaining: 4.34s
139:	learn: 0.7650804	total: 573ms	remaining: 4.34s
140:	learn: 0.7627695	total: 578ms	remaining: 4.34s
141:	learn: 0.7606279	total: 582ms	remaining: 4.33s
142:	learn: 0.7585685	total: 585ms	remaining: 4.33s
143:	learn: 0.7534483	total: 589ms	remaining: 4.32s
144:	learn: 0.7512609	total: 593ms	remaining: 4.32s
145:	learn: 0.7485125	total: 598ms	remaining: 4.32s
146:	learn: 0.7463744	total: 602ms	remaining: 4.31s
147:	learn: 0.7443820	total: 606ms	remaining: 4.31s
148:	learn: 0.7422180	total: 611ms	remaining: 4.31s
149:	learn: 0.7397492	total: 618ms	remaining: 4.32s
150:	learn: 0.7349306	total: 622ms	remaining: 4.32s
151:	learn: 0.7323885	total: 629ms	remaining: 4.33s
152:	learn: 0.7302568	total: 634ms	remaining: 4.34s
153:	learn: 0.7283165	total: 640ms	remaining: 4.35s
154:	learn: 0.7239088	total: 644ms	remaining: 4.34s
155:	learn: 0.7221289	total: 648ms	remaining: 4.34s
156:	learn: 0.7202989	total: 654ms	remaining: 4.34s
157:	learn: 0.7185745	total: 658ms	remaining: 4.34s
158:	learn: 0.7165334	total: 662ms	remaining: 4.33s
159:	learn: 0.7124000	total: 666ms	remaining: 4.33s
160:	learn: 0.7105852	total: 671ms	remaining: 4.33s
161:	learn: 0.7087192	total: 675ms	remaining: 4.32s
162:	learn: 0.7070659	total: 679ms	remaining: 4.32s
163:	learn: 0.7047288	total: 683ms	remaining: 4.32s
164:	learn: 0.7030500	total: 688ms	remaining: 4.32s
165:	learn: 0.6991929	total: 693ms	remaining: 4.31s
166:	learn: 0.6975757	total: 697ms	remaining: 4.31s
167:	learn: 0.6959264	total: 702ms	remaining: 4.31s
168:	learn: 0.6941913	total: 707ms	remaining: 4.31s
169:	learn: 0.6925726	total: 711ms	remaining: 4.31s
170:	learn: 0.6889849	total: 715ms	remaining: 4.3s
171:	learn: 0.6872398	total: 719ms	remaining: 4.29s
172:	learn: 0.6840389	total: 723ms	remaining: 4.29s
173:	learn: 0.6823859	total: 727ms	remaining: 4.29s
174:	learn: 0.6810461	total: 731ms	remaining: 4.28s
175:	learn: 0.6797091	total: 736ms	remaining: 4.28s
176:	learn: 0.6781581	total: 740ms	remaining: 4.28s
177:	learn: 0.6757914	total: 745ms	remaining: 4.28s
178:	learn: 0.6745713	total: 749ms	remaining: 4.27s
179:	learn: 0.6731916	total: 753ms	remaining: 4.27s
180:	learn: 0.6713370	total: 758ms	remaining: 4.27s
181:	learn: 0.6699574	total: 762ms	remaining: 4.26s
182:	learn: 0.6687334	total: 766ms	remaining: 4.26s
183:	learn: 0.6673723	total: 770ms	remaining: 4.25s
184:	learn: 0.6661065	total: 774ms	remaining: 4.25s
185:	learn: 0.6647879	total: 779ms	remaining: 4.25s
186:	learn: 0.6629883	total: 783ms	remaining: 4.24s
187:	learn: 0.6616833	total: 788ms	remaining: 4.24s
188:	learn: 0.6587369	total: 791ms	remaining: 4.23s
189:	learn: 0.6575679	total: 794ms	remaining: 4.22s
190:	learn: 0.6564105	total: 798ms	remaining: 4.22s
191:	learn: 0.6552968	total: 803ms	remaining: 4.22s
192:	learn: 0.6533898	total: 809ms	remaining: 4.22s
193:	learn: 0.6516554	total: 813ms	remaining: 4.21s
194:	learn: 0.6505340	total: 817ms	remaining: 4.21s
195:	learn: 0.6494695	total: 822ms	remaining: 4.21s
196:	learn: 0.6482960	total: 827ms	remaining: 4.21s
197:	learn: 0.6455305	total: 832ms	remaining: 4.21s
198:	learn: 0.6443863	total: 837ms	remaining: 4.21s
199:	learn: 0.6432243	total: 842ms	remaining: 4.21s
200:	learn: 0.6420255	total: 848ms	remaining: 4.22s
201:	learn: 0.6408275	total: 858ms	remaining: 4.24s
202:	learn: 0.6396579	total: 866ms	remaining: 4.25s
203:	learn: 0.6385204	total: 872ms	remaining: 4.26s
204:	learn: 0.6375197	total: 878ms	remaining: 4.26s
205:	learn: 0.6364291	total: 883ms	remaining: 4.26s
206:	learn: 0.6339698	total: 891ms	remaining: 4.27s
207:	learn: 0.6329544	total: 896ms	remaining: 4.27s
208:	learn: 0.6312780	total: 901ms	remaining: 4.27s
209:	learn: 0.6301789	total: 905ms	remaining: 4.26s
210:	learn: 0.6291889	total: 909ms	remaining: 4.26s
211:	learn: 0.6280661	total: 914ms	remaining: 4.26s
212:	learn: 0.6265538	total: 921ms	remaining: 4.27s
213:	learn: 0.6256356	total: 925ms	remaining: 4.26s
214:	learn: 0.6241603	total: 929ms	remaining: 4.26s
215:	learn: 0.6225785	total: 933ms	remaining: 4.25s
216:	learn: 0.6216178	total: 937ms	remaining: 4.24s
217:	learn: 0.6208169	total: 941ms	remaining: 4.24s
218:	learn: 0.6199643	total: 946ms	remaining: 4.24s
219:	learn: 0.6184430	total: 950ms	remaining: 4.23s
220:	learn: 0.6175323	total: 954ms	remaining: 4.23s
221:	learn: 0.6153874	total: 958ms	remaining: 4.22s
222:	learn: 0.6133143	total: 963ms	remaining: 4.22s
223:	learn: 0.6125619	total: 966ms	remaining: 4.21s
224:	learn: 0.6117555	total: 971ms	remaining: 4.21s
225:	learn: 0.6108764	total: 976ms	remaining: 4.21s
226:	learn: 0.6099479	total: 981ms	remaining: 4.2s
227:	learn: 0.6090782	total: 984ms	remaining: 4.2s
228:	learn: 0.6082928	total: 989ms	remaining: 4.19s
229:	learn: 0.6075859	total: 994ms	remaining: 4.19s
230:	learn: 0.6062851	total: 999ms	remaining: 4.19s
231:	learn: 0.6050675	total: 1s	remaining: 4.19s
232:	learn: 0.6042292	total: 1.01s	remaining: 4.18s
233:	learn: 0.6028138	total: 1.01s	remaining: 4.19s
234:	learn: 0.6019733	total: 1.02s	remaining: 4.19s
235:	learn: 0.6011957	total: 1.02s	remaining: 4.19s
236:	learn: 0.6003638	total: 1.03s	remaining: 4.18s
237:	learn: 0.5997480	total: 1.03s	remaining: 4.18s
238:	learn: 0.5989760	total: 1.04s	remaining: 4.18s
239:	learn: 0.5971090	total: 1.05s	remaining: 4.18s
240:	learn: 0.5964303	total: 1.05s	remaining: 4.18s
241:	learn: 0.5952542	total: 1.05s	remaining: 4.18s
242:	learn: 0.5941081	total: 1.06s	remaining: 4.17s
243:	learn: 0.5930628	total: 1.06s	remaining: 4.17s
244:	learn: 0.5923270	total: 1.07s	remaining: 4.17s
245:	learn: 0.5916739	total: 1.07s	remaining: 4.16s
246:	learn: 0.5909274	total: 1.08s	remaining: 4.16s
247:	learn: 0.5902609	total: 1.08s	remaining: 4.15s
248:	learn: 0.5895263	total: 1.09s	remaining: 4.15s
249:	learn: 0.5887986	total: 1.09s	remaining: 4.14s
250:	learn: 0.5881818	total: 1.09s	remaining: 4.14s
251:	learn: 0.5874601	total: 1.1s	remaining: 4.13s
252:	learn: 0.5857035	total: 1.1s	remaining: 4.13s
253:	learn: 0.5844526	total: 1.11s	remaining: 4.13s
254:	learn: 0.5836954	total: 1.11s	remaining: 4.13s
255:	learn: 0.5821071	total: 1.12s	remaining: 4.12s
256:	learn: 0.5814587	total: 1.12s	remaining: 4.12s
257:	learn: 0.5805310	total: 1.13s	remaining: 4.12s
258:	learn: 0.5798844	total: 1.13s	remaining: 4.11s
259:	learn: 0.5792579	total: 1.14s	remaining: 4.11s
260:	learn: 0.5785611	total: 1.14s	remaining: 4.11s
261:	learn: 0.5778770	total: 1.15s	remaining: 4.1s
262:	learn: 0.5771624	total: 1.15s	remaining: 4.1s
263:	learn: 0.5765208	total: 1.16s	remaining: 4.1s
264:	learn: 0.5759998	total: 1.16s	remaining: 4.09s
265:	learn: 0.5748780	total: 1.16s	remaining: 4.09s
266:	learn: 0.5734161	total: 1.17s	remaining: 4.08s
267:	learn: 0.5727839	total: 1.17s	remaining: 4.09s
268:	learn: 0.5722927	total: 1.18s	remaining: 4.08s
269:	learn: 0.5713691	total: 1.18s	remaining: 4.08s
270:	learn: 0.5704612	total: 1.19s	remaining: 4.07s
271:	learn: 0.5698576	total: 1.19s	remaining: 4.07s
272:	learn: 0.5686177	total: 1.2s	remaining: 4.07s
273:	learn: 0.5680224	total: 1.2s	remaining: 4.07s
274:	learn: 0.5674363	total: 1.21s	remaining: 4.06s
275:	learn: 0.5666206	total: 1.21s	remaining: 4.06s
276:	learn: 0.5658022	total: 1.22s	remaining: 4.06s
277:	learn: 0.5653294	total: 1.22s	remaining: 4.05s
278:	learn: 0.5647626	total: 1.23s	remaining: 4.05s
279:	learn: 0.5635461	total: 1.23s	remaining: 4.05s
280:	learn: 0.5629727	total: 1.24s	remaining: 4.05s
281:	learn: 0.5625213	total: 1.24s	remaining: 4.05s
282:	learn: 0.5619935	total: 1.25s	remaining: 4.04s
283:	learn: 0.5614588	total: 1.25s	remaining: 4.03s
284:	learn: 0.5609227	total: 1.25s	remaining: 4.03s
285:	learn: 0.5601570	total: 1.26s	remaining: 4.02s
286:	learn: 0.5592015	total: 1.26s	remaining: 4.02s
287:	learn: 0.5584176	total: 1.27s	remaining: 4.01s
288:	learn: 0.5573941	total: 1.27s	remaining: 4s
289:	learn: 0.5568844	total: 1.27s	remaining: 4s
290:	learn: 0.5563480	total: 1.28s	remaining: 4s
291:	learn: 0.5558370	total: 1.28s	remaining: 3.99s
292:	learn: 0.5553299	total: 1.29s	remaining: 3.98s
293:	learn: 0.5548141	total: 1.29s	remaining: 3.98s
294:	learn: 0.5544045	total: 1.29s	remaining: 3.97s
295:	learn: 0.5537263	total: 1.3s	remaining: 3.96s
296:	learn: 0.5532265	total: 1.3s	remaining: 3.96s
297:	learn: 0.5527348	total: 1.31s	remaining: 3.96s
298:	learn: 0.5517058	total: 1.31s	remaining: 3.95s
299:	learn: 0.5512626	total: 1.31s	remaining: 3.95s
300:	learn: 0.5508582	total: 1.32s	remaining: 3.94s
301:	learn: 0.5501659	total: 1.32s	remaining: 3.94s
302:	learn: 0.5495389	total: 1.33s	remaining: 3.94s
303:	learn: 0.5491010	total: 1.33s	remaining: 3.93s
304:	learn: 0.5485996	total: 1.34s	remaining: 3.93s
305:	learn: 0.5476645	total: 1.34s	remaining: 3.92s
306:	learn: 0.5472361	total: 1.35s	remaining: 3.92s
307:	learn: 0.5464600	total: 1.35s	remaining: 3.91s
308:	learn: 0.5459806	total: 1.36s	remaining: 3.91s
309:	learn: 0.5455703	total: 1.36s	remaining: 3.91s
310:	learn: 0.5450605	total: 1.36s	remaining: 3.9s
311:	learn: 0.5444187	total: 1.37s	remaining: 3.9s
312:	learn: 0.5439581	total: 1.37s	remaining: 3.9s
313:	learn: 0.5430706	total: 1.38s	remaining: 3.89s
314:	learn: 0.5426482	total: 1.38s	remaining: 3.88s
315:	learn: 0.5423037	total: 1.39s	remaining: 3.88s
316:	learn: 0.5419634	total: 1.39s	remaining: 3.88s
317:	learn: 0.5414904	total: 1.4s	remaining: 3.87s
318:	learn: 0.5410821	total: 1.4s	remaining: 3.86s
319:	learn: 0.5402957	total: 1.4s	remaining: 3.86s
320:	learn: 0.5396050	total: 1.41s	remaining: 3.86s
321:	learn: 0.5391722	total: 1.41s	remaining: 3.85s
322:	learn: 0.5387208	total: 1.42s	remaining: 3.85s
323:	learn: 0.5383025	total: 1.42s	remaining: 3.84s
324:	learn: 0.5378928	total: 1.43s	remaining: 3.84s
325:	learn: 0.5375234	total: 1.43s	remaining: 3.83s
326:	learn: 0.5371193	total: 1.44s	remaining: 3.83s
327:	learn: 0.5367266	total: 1.44s	remaining: 3.83s
328:	learn: 0.5362937	total: 1.45s	remaining: 3.83s
329:	learn: 0.5357363	total: 1.45s	remaining: 3.82s
330:	learn: 0.5349729	total: 1.45s	remaining: 3.82s
331:	learn: 0.5346530	total: 1.46s	remaining: 3.81s
332:	learn: 0.5340626	total: 1.46s	remaining: 3.81s
333:	learn: 0.5337342	total: 1.47s	remaining: 3.8s
334:	learn: 0.5333697	total: 1.47s	remaining: 3.79s
335:	learn: 0.5328875	total: 1.47s	remaining: 3.79s
336:	learn: 0.5322619	total: 1.48s	remaining: 3.78s
337:	learn: 0.5318588	total: 1.48s	remaining: 3.78s
338:	learn: 0.5315288	total: 1.49s	remaining: 3.78s
339:	learn: 0.5308753	total: 1.5s	remaining: 3.78s
340:	learn: 0.5304861	total: 1.5s	remaining: 3.78s
341:	learn: 0.5300725	total: 1.51s	remaining: 3.78s
342:	learn: 0.5296811	total: 1.51s	remaining: 3.78s
343:	learn: 0.5292912	total: 1.52s	remaining: 3.77s
344:	learn: 0.5289399	total: 1.52s	remaining: 3.77s
345:	learn: 0.5285441	total: 1.53s	remaining: 3.78s
346:	learn: 0.5282350	total: 1.53s	remaining: 3.77s
347:	learn: 0.5275846	total: 1.54s	remaining: 3.77s
348:	learn: 0.5272349	total: 1.54s	remaining: 3.76s
349:	learn: 0.5267050	total: 1.55s	remaining: 3.76s
350:	learn: 0.5263675	total: 1.55s	remaining: 3.75s
351:	learn: 0.5260742	total: 1.55s	remaining: 3.75s
352:	learn: 0.5257032	total: 1.56s	remaining: 3.74s
353:	learn: 0.5253457	total: 1.56s	remaining: 3.74s
354:	learn: 0.5249487	total: 1.57s	remaining: 3.73s
355:	learn: 0.5243624	total: 1.57s	remaining: 3.72s
356:	learn: 0.5240230	total: 1.57s	remaining: 3.72s
357:	learn: 0.5237505	total: 1.58s	remaining: 3.71s
358:	learn: 0.5234270	total: 1.58s	remaining: 3.7s
359:	learn: 0.5231493	total: 1.58s	remaining: 3.7s
360:	learn: 0.5228603	total: 1.59s	remaining: 3.7s
361:	learn: 0.5225266	total: 1.59s	remaining: 3.69s
362:	learn: 0.5221249	total: 1.6s	remaining: 3.69s
363:	learn: 0.5218190	total: 1.6s	remaining: 3.68s
364:	learn: 0.5214745	total: 1.61s	remaining: 3.68s
365:	learn: 0.5211705	total: 1.61s	remaining: 3.67s
366:	learn: 0.5204773	total: 1.61s	remaining: 3.67s
367:	learn: 0.5199541	total: 1.62s	remaining: 3.66s
368:	learn: 0.5196727	total: 1.63s	remaining: 3.66s
369:	learn: 0.5193126	total: 1.63s	remaining: 3.66s
370:	learn: 0.5190768	total: 1.64s	remaining: 3.65s
371:	learn: 0.5187228	total: 1.64s	remaining: 3.65s
372:	learn: 0.5183051	total: 1.64s	remaining: 3.64s
373:	learn: 0.5179920	total: 1.65s	remaining: 3.64s
374:	learn: 0.5174798	total: 1.65s	remaining: 3.63s
375:	learn: 0.5171452	total: 1.65s	remaining: 3.63s
376:	learn: 0.5166229	total: 1.66s	remaining: 3.62s
377:	learn: 0.5163921	total: 1.66s	remaining: 3.62s
378:	learn: 0.5160810	total: 1.67s	remaining: 3.61s
379:	learn: 0.5158159	total: 1.67s	remaining: 3.61s
380:	learn: 0.5154862	total: 1.68s	remaining: 3.6s
381:	learn: 0.5152181	total: 1.68s	remaining: 3.6s
382:	learn: 0.5148736	total: 1.68s	remaining: 3.59s
383:	learn: 0.5146375	total: 1.69s	remaining: 3.59s
384:	learn: 0.5143543	total: 1.69s	remaining: 3.59s
385:	learn: 0.5140305	total: 1.7s	remaining: 3.58s
386:	learn: 0.5135660	total: 1.7s	remaining: 3.58s

RandomizedSearchCV(cv=5,
                   estimator=Pipeline(steps=[('Preprocessing',
                                              ColumnTransformer(remainder='passthrough',
                                                                transformers=[('Num '
                                                                               'Pipeline',
                                                                               Pipeline(steps=[('Scaler',
                                                                                                MinMaxScaler())]),
                                                                               Index(['dialysisrenalendstage', 'asthma', 'irondef', 'pneum',
       'substancedependence', 'psychologicaldisordermajor', 'depress',
       'psychother', 'fibrosisandother', 'malnutrition',...
                                                                               Pipeline(steps=[('Binary '
                                                                                                'Encoder',
                                                                                                BinaryEncoder())]),
                                                                               Index(['rcount', 'gender'], dtype='object'))])),
                                             ('Model',
                                              CatBoostRegressor(loss_function='RMSE', random_state=42))]),
                   n_jobs=1,
                   param_distributions={'Model__depth': [4, 6, 8],
                                        'Model__iterations': [500, 800, 1200],
                                        'Model__learning_rate': [0.01, 0.03,
                                                                 0.05]},
                   random_state=42, return_train_score=True, scoring='r2')

In [18]:
random_search.best_score_

np.float64(0.9720784995304659)

In [19]:
random_search.best_params_

{'Model__learning_rate': 0.05, 'Model__iterations': 1200, 'Model__depth': 6}

In [20]:
train_scores = random_search.cv_results_['mean_train_score'] * 100
train_scores

array([96.71631865, 97.07973295, 91.11498626, 96.04206204, 86.03541174,
       97.11589069, 97.34115353, 97.55284304, 94.48058656, 96.99725869])

In [21]:
test_scores = random_search.cv_results_['mean_test_score'] * 100
test_scores

array([96.55527593, 96.9182431 , 91.00767584, 95.76398506, 85.98598835,
       96.9485944 , 97.11784415, 97.20784995, 94.372082  , 96.71545309])

In [22]:
px.scatter(x= train_scores, y= test_scores, labels= {'x' : 'Train Scores', 'y' : 'Test Scores'})

In [23]:
catboost_final_pipeline =  Pipeline(steps= [ ('Preprocessing', preprocessing), ('Model', CatBoostRegressor(random_state = 42))])
catboost_final_pipeline

Pipeline(steps=[('Preprocessing',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('Num Pipeline',
                                                  Pipeline(steps=[('Scaler',
                                                                   MinMaxScaler())]),
                                                  Index(['dialysisrenalendstage', 'asthma', 'irondef', 'pneum',
       'substancedependence', 'psychologicaldisordermajor', 'depress',
       'psychother', 'fibrosisandother', 'malnutrition', 'hemo', 'hematocrit',
       'neutrophils', 'sodium', 'glucose', 'bloodureanitro', 'creatinine',
       'bmi', 'pulse', 'respiration'],
      dtype='object')),
                                                 ('Cat Pipeline',
                                                  Pipeline(steps=[('Binary '
                                                                   'Encoder',
                                                                   BinaryEncoder())]),
                                                  Index(['rcount', 'gender'], dtype='object'))])),
                ('Model',
                 CatBoostRegressor(loss_function='RMSE', random_state=42))])

In [24]:
catboost_final_pipeline.fit(x, y)

Learning rate set to 0.084758
0:	learn: 2.2180004	total: 7.4ms	remaining: 7.39s
1:	learn: 2.0904256	total: 14.1ms	remaining: 7.04s
2:	learn: 1.9765605	total: 20.5ms	remaining: 6.8s
3:	learn: 1.8770745	total: 26.3ms	remaining: 6.54s
4:	learn: 1.7860127	total: 31.9ms	remaining: 6.35s
5:	learn: 1.7041964	total: 37.2ms	remaining: 6.17s
6:	learn: 1.6325004	total: 43.3ms	remaining: 6.14s
7:	learn: 1.5669052	total: 48.1ms	remaining: 5.96s
8:	learn: 1.5086945	total: 52.4ms	remaining: 5.77s
9:	learn: 1.4575266	total: 58.1ms	remaining: 5.75s
10:	learn: 1.4121503	total: 64.3ms	remaining: 5.78s
11:	learn: 1.3723683	total: 69.5ms	remaining: 5.72s
12:	learn: 1.3351111	total: 77.4ms	remaining: 5.87s
13:	learn: 1.3027495	total: 83.1ms	remaining: 5.85s
14:	learn: 1.2719277	total: 89.6ms	remaining: 5.88s
15:	learn: 1.2434238	total: 94.5ms	remaining: 5.81s
16:	learn: 1.2175118	total: 99.2ms	remaining: 5.74s
17:	learn: 1.1928177	total: 104ms	remaining: 5.69s
18:	learn: 1.1714107	total: 110ms	remaining: 5.67s
19:	learn: 1.1497824	total: 116ms	remaining: 5.68s
20:	learn: 1.1304709	total: 123ms	remaining: 5.71s
21:	learn: 1.1112559	total: 128ms	remaining: 5.7s
22:	learn: 1.0925909	total: 133ms	remaining: 5.66s
23:	learn: 1.0749261	total: 138ms	remaining: 5.62s
24:	learn: 1.0564795	total: 144ms	remaining: 5.61s
25:	learn: 1.0391602	total: 150ms	remaining: 5.63s
26:	learn: 1.0235352	total: 156ms	remaining: 5.64s
27:	learn: 1.0071566	total: 163ms	remaining: 5.66s
28:	learn: 0.9907043	total: 171ms	remaining: 5.72s
29:	learn: 0.9762613	total: 176ms	remaining: 5.7s
30:	learn: 0.9622889	total: 183ms	remaining: 5.71s
31:	learn: 0.9474761	total: 189ms	remaining: 5.71s
32:	learn: 0.9337903	total: 194ms	remaining: 5.67s
33:	learn: 0.9214651	total: 200ms	remaining: 5.69s
34:	learn: 0.9086393	total: 205ms	remaining: 5.66s
35:	learn: 0.8959121	total: 211ms	remaining: 5.64s
36:	learn: 0.8825615	total: 216ms	remaining: 5.62s
37:	learn: 0.8710491	total: 223ms	remaining: 5.64s
38:	learn: 0.8601253	total: 229ms	remaining: 5.65s
39:	learn: 0.8490342	total: 236ms	remaining: 5.66s
40:	learn: 0.8377264	total: 243ms	remaining: 5.69s
41:	learn: 0.8276442	total: 249ms	remaining: 5.69s
42:	learn: 0.8157686	total: 255ms	remaining: 5.67s
43:	learn: 0.8056314	total: 260ms	remaining: 5.65s
44:	learn: 0.7969636	total: 266ms	remaining: 5.65s
45:	learn: 0.7881867	total: 271ms	remaining: 5.63s
46:	learn: 0.7795685	total: 276ms	remaining: 5.6s
47:	learn: 0.7710237	total: 281ms	remaining: 5.58s
48:	learn: 0.7613328	total: 287ms	remaining: 5.57s
49:	learn: 0.7529102	total: 294ms	remaining: 5.58s
50:	learn: 0.7444618	total: 300ms	remaining: 5.58s
51:	learn: 0.7367726	total: 308ms	remaining: 5.61s
52:	learn: 0.7296097	total: 314ms	remaining: 5.62s
53:	learn: 0.7222976	total: 322ms	remaining: 5.63s
54:	learn: 0.7148254	total: 329ms	remaining: 5.66s
55:	learn: 0.7063849	total: 338ms	remaining: 5.71s
56:	learn: 0.7001618	total: 345ms	remaining: 5.7s
57:	learn: 0.6937991	total: 352ms	remaining: 5.72s
58:	learn: 0.6877061	total: 359ms	remaining: 5.73s
59:	learn: 0.6819370	total: 367ms	remaining: 5.75s
60:	learn: 0.6749984	total: 374ms	remaining: 5.75s
61:	learn: 0.6689061	total: 381ms	remaining: 5.77s
62:	learn: 0.6625393	total: 386ms	remaining: 5.74s
63:	learn: 0.6571310	total: 392ms	remaining: 5.73s
64:	learn: 0.6521735	total: 398ms	remaining: 5.72s
65:	learn: 0.6467218	total: 407ms	remaining: 5.76s
66:	learn: 0.6420623	total: 414ms	remaining: 5.76s
67:	learn: 0.6359402	total: 420ms	remaining: 5.76s
68:	learn: 0.6312374	total: 430ms	remaining: 5.8s
69:	learn: 0.6267939	total: 436ms	remaining: 5.79s
70:	learn: 0.6218122	total: 444ms	remaining: 5.81s
71:	learn: 0.6173792	total: 451ms	remaining: 5.82s
72:	learn: 0.6133757	total: 457ms	remaining: 5.8s
73:	learn: 0.6090806	total: 465ms	remaining: 5.82s
74:	learn: 0.6055252	total: 474ms	remaining: 5.85s
75:	learn: 0.6016886	total: 480ms	remaining: 5.83s
76:	learn: 0.5985455	total: 485ms	remaining: 5.81s
77:	learn: 0.5941973	total: 493ms	remaining: 5.83s
78:	learn: 0.5904858	total: 501ms	remaining: 5.84s
79:	learn: 0.5875248	total: 508ms	remaining: 5.84s
80:	learn: 0.5846795	total: 513ms	remaining: 5.82s
81:	learn: 0.5810434	total: 518ms	remaining: 5.8s
82:	learn: 0.5777263	total: 524ms	remaining: 5.79s
83:	learn: 0.5744362	total: 529ms	remaining: 5.77s
84:	learn: 0.5719496	total: 535ms	remaining: 5.76s
85:	learn: 0.5692081	total: 542ms	remaining: 5.76s
86:	learn: 0.5669332	total: 547ms	remaining: 5.74s
87:	learn: 0.5646698	total: 551ms	remaining: 5.71s
88:	learn: 0.5607002	total: 556ms	remaining: 5.69s
89:	learn: 0.5570495	total: 560ms	remaining: 5.66s
90:	learn: 0.5544878	total: 565ms	remaining: 5.64s
91:	learn: 0.5519185	total: 570ms	remaining: 5.63s
92:	learn: 0.5495272	total: 575ms	remaining: 5.61s
93:	learn: 0.5469523	total: 579ms	remaining: 5.58s
94:	learn: 0.5450225	total: 585ms	remaining: 5.57s
95:	learn: 0.5431752	total: 590ms	remaining: 5.56s
96:	learn: 0.5397536	total: 595ms	remaining: 5.54s
97:	learn: 0.5380311	total: 601ms	remaining: 5.53s
98:	learn: 0.5357945	total: 605ms	remaining: 5.5s
99:	learn: 0.5337139	total: 609ms	remaining: 5.48s
100:	learn: 0.5322079	total: 616ms	remaining: 5.48s
101:	learn: 0.5306134	total: 623ms	remaining: 5.48s
102:	learn: 0.5271770	total: 629ms	remaining: 5.48s
103:	learn: 0.5254063	total: 635ms	remaining: 5.47s
104:	learn: 0.5239317	total: 641ms	remaining: 5.46s
105:	learn: 0.5219844	total: 646ms	remaining: 5.45s
106:	learn: 0.5204873	total: 651ms	remaining: 5.43s
107:	learn: 0.5185655	total: 655ms	remaining: 5.41s
108:	learn: 0.5159398	total: 660ms	remaining: 5.39s
109:	learn: 0.5145376	total: 664ms	remaining: 5.38s
110:	learn: 0.5131084	total: 670ms	remaining: 5.36s
111:	learn: 0.5115504	total: 675ms	remaining: 5.35s
112:	learn: 0.5103424	total: 681ms	remaining: 5.34s
113:	learn: 0.5076148	total: 685ms	remaining: 5.33s
114:	learn: 0.5062075	total: 690ms	remaining: 5.31s
115:	learn: 0.5041640	total: 695ms	remaining: 5.3s
116:	learn: 0.5028553	total: 700ms	remaining: 5.28s
117:	learn: 0.5013930	total: 705ms	remaining: 5.27s
118:	learn: 0.4998397	total: 710ms	remaining: 5.25s
119:	learn: 0.4987312	total: 715ms	remaining: 5.25s
120:	learn: 0.4978591	total: 721ms	remaining: 5.24s
121:	learn: 0.4965838	total: 727ms	remaining: 5.23s
122:	learn: 0.4953165	total: 734ms	remaining: 5.24s
123:	learn: 0.4932752	total: 740ms	remaining: 5.23s
124:	learn: 0.4919633	total: 747ms	remaining: 5.23s
125:	learn: 0.4908562	total: 753ms	remaining: 5.23s
126:	learn: 0.4893805	total: 760ms	remaining: 5.22s
127:	learn: 0.4881647	total: 766ms	remaining: 5.22s
128:	learn: 0.4870753	total: 772ms	remaining: 5.21s
129:	learn: 0.4859313	total: 778ms	remaining: 5.21s
130:	learn: 0.4840784	total: 785ms	remaining: 5.21s
131:	learn: 0.4829412	total: 791ms	remaining: 5.2s
132:	learn: 0.4817754	total: 796ms	remaining: 5.19s
133:	learn: 0.4805775	total: 803ms	remaining: 5.19s
134:	learn: 0.4797332	total: 811ms	remaining: 5.19s
135:	learn: 0.4788365	total: 818ms	remaining: 5.19s
136:	learn: 0.4774309	total: 825ms	remaining: 5.2s
137:	learn: 0.4762593	total: 831ms	remaining: 5.19s
138:	learn: 0.4751843	total: 837ms	remaining: 5.19s
139:	learn: 0.4741641	total: 843ms	remaining: 5.18s
140:	learn: 0.4732937	total: 850ms	remaining: 5.18s
141:	learn: 0.4726470	total: 856ms	remaining: 5.17s
142:	learn: 0.4710573	total: 863ms	remaining: 5.17s
143:	learn: 0.4701185	total: 869ms	remaining: 5.17s
144:	learn: 0.4688228	total: 875ms	remaining: 5.16s
145:	learn: 0.4677765	total: 880ms	remaining: 5.15s
146:	learn: 0.4669956	total: 886ms	remaining: 5.14s
147:	learn: 0.4662180	total: 892ms	remaining: 5.13s
148:	learn: 0.4645758	total: 898ms	remaining: 5.13s
149:	learn: 0.4635581	total: 905ms	remaining: 5.13s
150:	learn: 0.4627388	total: 911ms	remaining: 5.12s
151:	learn: 0.4619063	total: 918ms	remaining: 5.12s
152:	learn: 0.4609899	total: 924ms	remaining: 5.12s
153:	learn: 0.4604190	total: 931ms	remaining: 5.12s
154:	learn: 0.4594573	total: 938ms	remaining: 5.12s
155:	learn: 0.4587062	total: 945ms	remaining: 5.11s
156:	learn: 0.4578757	total: 952ms	remaining: 5.11s
157:	learn: 0.4570250	total: 958ms	remaining: 5.11s
158:	learn: 0.4562343	total: 965ms	remaining: 5.11s
159:	learn: 0.4557200	total: 972ms	remaining: 5.1s
160:	learn: 0.4545026	total: 979ms	remaining: 5.1s
161:	learn: 0.4537526	total: 985ms	remaining: 5.09s
162:	learn: 0.4529791	total: 991ms	remaining: 5.09s
163:	learn: 0.4522082	total: 997ms	remaining: 5.08s
164:	learn: 0.4516406	total: 1s	remaining: 5.08s
165:	learn: 0.4508708	total: 1.01s	remaining: 5.08s
166:	learn: 0.4498721	total: 1.02s	remaining: 5.09s
167:	learn: 0.4491767	total: 1.03s	remaining: 5.09s
168:	learn: 0.4484768	total: 1.04s	remaining: 5.11s
169:	learn: 0.4478015	total: 1.05s	remaining: 5.11s
170:	learn: 0.4472635	total: 1.05s	remaining: 5.11s
171:	learn: 0.4463613	total: 1.06s	remaining: 5.11s
172:	learn: 0.4456249	total: 1.07s	remaining: 5.11s
173:	learn: 0.4449611	total: 1.07s	remaining: 5.1s
174:	learn: 0.4440759	total: 1.08s	remaining: 5.1s
175:	learn: 0.4433668	total: 1.09s	remaining: 5.09s
176:	learn: 0.4426820	total: 1.09s	remaining: 5.09s
177:	learn: 0.4421897	total: 1.1s	remaining: 5.09s
178:	learn: 0.4415401	total: 1.11s	remaining: 5.09s
179:	learn: 0.4410319	total: 1.12s	remaining: 5.09s
180:	learn: 0.4402604	total: 1.12s	remaining: 5.09s
181:	learn: 0.4397296	total: 1.13s	remaining: 5.08s
182:	learn: 0.4391001	total: 1.14s	remaining: 5.08s
183:	learn: 0.4386981	total: 1.14s	remaining: 5.07s
184:	learn: 0.4383081	total: 1.15s	remaining: 5.07s
185:	learn: 0.4378022	total: 1.16s	remaining: 5.07s
186:	learn: 0.4369900	total: 1.16s	remaining: 5.06s
187:	learn: 0.4364144	total: 1.17s	remaining: 5.05s
188:	learn: 0.4357269	total: 1.18s	remaining: 5.04s
189:	learn: 0.4351213	total: 1.18s	remaining: 5.03s
190:	learn: 0.4346016	total: 1.19s	remaining: 5.02s
191:	learn: 0.4338331	total: 1.19s	remaining: 5.01s
192:	learn: 0.4333551	total: 1.2s	remaining: 5.01s
193:	learn: 0.4327808	total: 1.2s	remaining: 5.01s
194:	learn: 0.4322000	total: 1.21s	remaining: 5s
195:	learn: 0.4316683	total: 1.22s	remaining: 5s
196:	learn: 0.4312559	total: 1.22s	remaining: 4.99s
197:	learn: 0.4307518	total: 1.23s	remaining: 4.99s
198:	learn: 0.4302001	total: 1.24s	remaining: 4.99s
199:	learn: 0.4296334	total: 1.24s	remaining: 4.98s
200:	learn: 0.4292143	total: 1.25s	remaining: 4.98s
201:	learn: 0.4284849	total: 1.26s	remaining: 4.97s
202:	learn: 0.4281238	total: 1.26s	remaining: 4.96s
203:	learn: 0.4277564	total: 1.27s	remaining: 4.96s
204:	learn: 0.4273350	total: 1.28s	remaining: 4.95s
205:	learn: 0.4268371	total: 1.28s	remaining: 4.94s
206:	learn: 0.4262939	total: 1.29s	remaining: 4.93s
207:	learn: 0.4258631	total: 1.29s	remaining: 4.93s
208:	learn: 0.4255317	total: 1.3s	remaining: 4.92s
209:	learn: 0.4250060	total: 1.31s	remaining: 4.92s
210:	learn: 0.4246032	total: 1.31s	remaining: 4.91s
211:	learn: 0.4241427	total: 1.32s	remaining: 4.9s
212:	learn: 0.4237049	total: 1.32s	remaining: 4.89s
213:	learn: 0.4233273	total: 1.33s	remaining: 4.89s
214:	learn: 0.4229179	total: 1.34s	remaining: 4.89s
215:	learn: 0.4225445	total: 1.34s	remaining: 4.88s
216:	learn: 0.4221394	total: 1.35s	remaining: 4.88s
217:	learn: 0.4217332	total: 1.36s	remaining: 4.87s
218:	learn: 0.4213485	total: 1.36s	remaining: 4.86s
219:	learn: 0.4210787	total: 1.37s	remaining: 4.85s
220:	learn: 0.4207842	total: 1.37s	remaining: 4.84s
221:	learn: 0.4204065	total: 1.38s	remaining: 4.83s
222:	learn: 0.4198109	total: 1.39s	remaining: 4.83s
223:	learn: 0.4194787	total: 1.39s	remaining: 4.82s
224:	learn: 0.4192000	total: 1.4s	remaining: 4.81s
225:	learn: 0.4189781	total: 1.4s	remaining: 4.81s
226:	learn: 0.4185474	total: 1.41s	remaining: 4.8s
227:	learn: 0.4182826	total: 1.42s	remaining: 4.8s
228:	learn: 0.4179302	total: 1.42s	remaining: 4.79s
229:	learn: 0.4176022	total: 1.43s	remaining: 4.79s
230:	learn: 0.4173731	total: 1.44s	remaining: 4.79s
231:	learn: 0.4170445	total: 1.44s	remaining: 4.78s
232:	learn: 0.4167716	total: 1.45s	remaining: 4.78s
233:	learn: 0.4164824	total: 1.46s	remaining: 4.77s
234:	learn: 0.4161788	total: 1.47s	remaining: 4.77s
235:	learn: 0.4159471	total: 1.47s	remaining: 4.76s
236:	learn: 0.4154981	total: 1.48s	remaining: 4.75s
237:	learn: 0.4152143	total: 1.48s	remaining: 4.74s
238:	learn: 0.4148429	total: 1.49s	remaining: 4.74s
239:	learn: 0.4145898	total: 1.49s	remaining: 4.73s
240:	learn: 0.4143351	total: 1.5s	remaining: 4.72s
241:	learn: 0.4139932	total: 1.5s	remaining: 4.72s
242:	learn: 0.4137802	total: 1.51s	remaining: 4.71s
243:	learn: 0.4134252	total: 1.52s	remaining: 4.71s
244:	learn: 0.4131069	total: 1.52s	remaining: 4.7s
245:	learn: 0.4127681	total: 1.53s	remaining: 4.7s
246:	learn: 0.4124578	total: 1.54s	remaining: 4.7s
247:	learn: 0.4121661	total: 1.55s	remaining: 4.69s
248:	learn: 0.4118203	total: 1.55s	remaining: 4.69s
249:	learn: 0.4116189	total: 1.56s	remaining: 4.7s
250:	learn: 0.4113839	total: 1.57s	remaining: 4.69s
251:	learn: 0.4110031	total: 1.58s	remaining: 4.68s
252:	learn: 0.4108889	total: 1.58s	remaining: 4.68s
253:	learn: 0.4106802	total: 1.59s	remaining: 4.67s
254:	learn: 0.4104389	total: 1.6s	remaining: 4.67s
255:	learn: 0.4103025	total: 1.6s	remaining: 4.66s
256:	learn: 0.4100379	total: 1.61s	remaining: 4.65s
257:	learn: 0.4096732	total: 1.61s	remaining: 4.64s
258:	learn: 0.4093991	total: 1.62s	remaining: 4.64s
259:	learn: 0.4091580	total: 1.63s	remaining: 4.63s
260:	learn: 0.4083822	total: 1.63s	remaining: 4.63s
261:	learn: 0.4081736	total: 1.64s	remaining: 4.62s
262:	learn: 0.4078694	total: 1.65s	remaining: 4.62s
263:	learn: 0.4076806	total: 1.66s	remaining: 4.62s
264:	learn: 0.4074505	total: 1.66s	remaining: 4.61s
265:	learn: 0.4072036	total: 1.67s	remaining: 4.6s
266:	learn: 0.4069844	total: 1.67s	remaining: 4.6s
267:	learn: 0.4065162	total: 1.68s	remaining: 4.59s
268:	learn: 0.4063038	total: 1.69s	remaining: 4.58s
269:	learn: 0.4060685	total: 1.69s	remaining: 4.57s
270:	learn: 0.4058810	total: 1.7s	remaining: 4.57s
271:	learn: 0.4050948	total: 1.7s	remaining: 4.56s
272:	learn: 0.4048327	total: 1.71s	remaining: 4.55s
273:	learn: 0.4046722	total: 1.72s	remaining: 4.55s
274:	learn: 0.4045643	total: 1.72s	remaining: 4.54s
275:	learn: 0.4043421	total: 1.73s	remaining: 4.54s
276:	learn: 0.4041016	total: 1.74s	remaining: 4.53s
277:	learn: 0.4039038	total: 1.74s	remaining: 4.53s
278:	learn: 0.4036501	total: 1.75s	remaining: 4.52s
279:	learn: 0.4035102	total: 1.76s	remaining: 4.51s
280:	learn: 0.4033213	total: 1.76s	remaining: 4.51s
281:	learn: 0.4031448	total: 1.77s	remaining: 4.5s
282:	learn: 0.4029755	total: 1.77s	remaining: 4.49s
283:	learn: 0.4023018	total: 1.78s	remaining: 4.49s
284:	learn: 0.4021664	total: 1.79s	remaining: 4.48s
285:	learn: 0.4019794	total: 1.79s	remaining: 4.47s
286:	learn: 0.4016861	total: 1.8s	remaining: 4.47s
287:	learn: 0.4015766	total: 1.8s	remaining: 4.46s
288:	learn: 0.4013715	total: 1.81s	remaining: 4.45s
289:	learn: 0.4012622	total: 1.81s	remaining: 4.45s
290:	learn: 0.4008943	total: 1.82s	remaining: 4.44s
291:	learn: 0.4007708	total: 1.83s	remaining: 4.44s
292:	learn: 0.4006172	total: 1.83s	remaining: 4.43s
293:	learn: 0.4004556	total: 1.84s	remaining: 4.42s
294:	learn: 0.4003151	total: 1.85s	remaining: 4.42s
295:	learn: 0.4001242	total: 1.85s	remaining: 4.41s
296:	learn: 0.3999748	total: 1.86s	remaining: 4.4s
297:	learn: 0.3997961	total: 1.86s	remaining: 4.39s
298:	learn: 0.3995612	total: 1.87s	remaining: 4.39s
299:	learn: 0.3989955	total: 1.88s	remaining: 4.38s
300:	learn: 0.3988009	total: 1.88s	remaining: 4.37s
301:	learn: 0.3986070	total: 1.89s	remaining: 4.37s
302:	learn: 0.3985111	total: 1.9s	remaining: 4.37s
303:	learn: 0.3983343	total: 1.9s	remaining: 4.36s
304:	learn: 0.3979431	total: 1.91s	remaining: 4.35s
305:	learn: 0.3977741	total: 1.92s	remaining: 4.35s
306:	learn: 0.3976111	total: 1.92s	remaining: 4.34s
307:	learn: 0.3974762	total: 1.93s	remaining: 4.34s
308:	learn: 0.3973120	total: 1.94s	remaining: 4.33s
309:	learn: 0.3971447	total: 1.94s	remaining: 4.33s
310:	learn: 0.3970326	total: 1.95s	remaining: 4.32s
311:	learn: 0.3968690	total: 1.96s	remaining: 4.32s
312:	learn: 0.3967312	total: 1.96s	remaining: 4.31s
313:	learn: 0.3965648	total: 1.97s	remaining: 4.3s
314:	learn: 0.3962361	total: 1.98s	remaining: 4.3s
315:	learn: 0.3960965	total: 1.98s	remaining: 4.29s
316:	learn: 0.3958894	total: 1.99s	remaining: 4.29s
317:	learn: 0.3957379	total: 2s	remaining: 4.28s
318:	learn: 0.3955715	total: 2s	remaining: 4.28s
319:	learn: 0.3954075	total: 2.01s	remaining: 4.27s
320:	learn: 0.3952443	total: 2.02s	remaining: 4.26s
321:	learn: 0.3951205	total: 2.02s	remaining: 4.26s
322:	learn: 0.3948764	total: 2.03s	remaining: 4.25s
323:	learn: 0.3947694	total: 2.04s	remaining: 4.25s
324:	learn: 0.3944935	total: 2.04s	remaining: 4.25s
325:	learn: 0.3943753	total: 2.05s	remaining: 4.24s
326:	learn: 0.3942945	total: 2.06s	remaining: 4.24s
327:	learn: 0.3941642	total: 2.06s	remaining: 4.23s
328:	learn: 0.3940422	total: 2.07s	remaining: 4.22s
329:	learn: 0.3939434	total: 2.08s	remaining: 4.22s
330:	learn: 0.3937580	total: 2.08s	remaining: 4.21s
331:	learn: 0.3936424	total: 2.09s	remaining: 4.2s
332:	learn: 0.3935271	total: 2.09s	remaining: 4.2s
333:	learn: 0.3933865	total: 2.1s	remaining: 4.19s
334:	learn: 0.3932221	total: 2.11s	remaining: 4.18s
335:	learn: 0.3931146	total: 2.11s	remaining: 4.17s
336:	learn: 0.3930232	total: 2.12s	remaining: 4.17s
337:	learn: 0.3929157	total: 2.13s	remaining: 4.16s
338:	learn: 0.3929057	total: 2.13s	remaining: 4.16s
339:	learn: 0.3927992	total: 2.14s	remaining: 4.15s
340:	learn: 0.3926689	total: 2.14s	remaining: 4.14s
341:	learn: 0.3925227	total: 2.15s	remaining: 4.14s
342:	learn: 0.3923890	total: 2.16s	remaining: 4.13s
343:	learn: 0.3922437	total: 2.16s	remaining: 4.12s
344:	learn: 0.3921164	total: 2.17s	remaining: 4.12s
345:	learn: 0.3920105	total: 2.17s	remaining: 4.11s
346:	learn: 0.3919036	total: 2.18s	remaining: 4.1s
347:	learn: 0.3917691	total: 2.19s	remaining: 4.09s
348:	learn: 0.3916587	total: 2.19s	remaining: 4.09s
349:	learn: 0.3915213	total: 2.2s	remaining: 4.08s
350:	learn: 0.3914249	total: 2.2s	remaining: 4.07s
351:	learn: 0.3912543	total: 2.21s	remaining: 4.07s
352:	learn: 0.3911432	total: 2.22s	remaining: 4.06s
353:	learn: 0.3910615	total: 2.22s	remaining: 4.05s
354:	learn: 0.3909180	total: 2.23s	remaining: 4.05s
355:	learn: 0.3908643	total: 2.23s	remaining: 4.04s
356:	learn: 0.3907374	total: 2.24s	remaining: 4.04s
357:	learn: 0.3906399	total: 2.25s	remaining: 4.04s
358:	learn: 0.3906055	total: 2.26s	remaining: 4.03s
359:	learn: 0.3905013	total: 2.27s	remaining: 4.03s
360:	learn: 0.3904054	total: 2.27s	remaining: 4.02s
361:	learn: 0.3902980	total: 2.28s	remaining: 4.02s
362:	learn: 0.3902197	total: 2.29s	remaining: 4.01s
363:	learn: 0.3900789	total: 2.29s	remaining: 4.01s
364:	learn: 0.3899279	total: 2.3s	remaining: 4s
365:	learn: 0.3898572	total: 2.31s	remaining: 4s
366:	learn: 0.3898562	total: 2.31s	remaining: 3.98s
367:	learn: 0.3897590	total: 2.32s	remaining: 3.98s
368:	learn: 0.3897566	total: 2.32s	remaining: 3.97s
369:	learn: 0.3897111	total: 2.33s	remaining: 3.97s
370:	learn: 0.3896084	total: 2.33s	remaining: 3.96s
371:	learn: 0.3894963	total: 2.34s	remaining: 3.95s
372:	learn: 0.3893540	total: 2.35s	remaining: 3.95s
373:	learn: 0.3892816	total: 2.35s	remaining: 3.94s
374:	learn: 0.3891590	total: 2.36s	remaining: 3.94s
375:	learn: 0.3890751	total: 2.37s	remaining: 3.94s
376:	learn: 0.3889288	total: 2.38s	remaining: 3.93s
377:	learn: 0.3888238	total: 2.38s	remaining: 3.92s
378:	learn: 0.3885617	total: 2.39s	remaining: 3.92s
379:	learn: 0.3884483	total: 2.4s	remaining: 3.92s
380:	learn: 0.3883398	total: 2.4s	remaining: 3.91s
381:	learn: 0.3882501	total: 2.41s	remaining: 3.9s
382:	learn: 0.3881336	total: 2.42s	remaining: 3.9s
383:	learn: 0.3880258	total: 2.43s	remaining: 3.89s
384:	learn: 0.3879055	total: 2.43s	remaining: 3.89s
385:	learn: 0.3878114	total: 2.44s	remaining: 3.88s
386:	learn: 0.3877083	total: 2.45s	remaining: 3.88s

Pipeline(steps=[('Preprocessing',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('Num Pipeline',
                                                  Pipeline(steps=[('Scaler',
                                                                   MinMaxScaler())]),
                                                  Index(['dialysisrenalendstage', 'asthma', 'irondef', 'pneum',
       'substancedependence', 'psychologicaldisordermajor', 'depress',
       'psychother', 'fibrosisandother', 'malnutrition', 'hemo', 'hematocrit',
       'neutrophils', 'sodium', 'glucose', 'bloodureanitro', 'creatinine',
       'bmi', 'pulse', 'respiration'],
      dtype='object')),
                                                 ('Cat Pipeline',
                                                  Pipeline(steps=[('Binary '
                                                                   'Encoder',
                                                                   BinaryEncoder())]),
                                                  Index(['rcount', 'gender'], dtype='object'))])),
                ('Model',
                 CatBoostRegressor(loss_function='RMSE', random_state=42))])

In [31]:
x.sample(random_state= 41)

,rcount,gender,dialysisrenalendstage,asthma,irondef,pneum,substancedependence,psychologicaldisordermajor,depress,psychother,...,hemo,hematocrit,neutrophils,sodium,glucose,bloodureanitro,creatinine,bmi,pulse,respiration
eid,,,,,,,,,,,,,,,,,,,,,
48284,0,M,0,0,0,0,0,0,0,0,...,0,14.9,7.8,135.09393,130.337141,14.0,0.949112,29.498411,67,6.5

In [33]:
catboost_final_pipeline.predict(x.sample(random_state= 41)).round(0)[0]

np.float64(1.0)

In [27]:
import joblib

joblib.dump(catboost_final_pipeline, 'Catboost_Model_LOS.pkl')

['Catboost_Model_LOS.pkl']

In [28]:
df.to_csv('Cleaned_df.csv', index=False)

In [29]:
import streamlit as st

In [30]:
! streamlit run app.py

^C

In [34]:
%%writefile app.py
import streamlit as st
import pandas as pd
import numpy as np
import pickle
import warnings
warnings.filterwarnings("ignore")

# ── Page config MUST be the first Streamlit command ────────────────────────────
st.set_page_config(
    page_title="LOS Predictor - Hospital Length of Stay",
    page_icon="🏥",
    layout="wide",
    initial_sidebar_state="expanded"
)

# ── Custom CSS for better styling ──────────────────────────────────────────────
st.markdown("""
<style>
    /* Main container styling */
    .main-header {
        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
        padding: 1.5rem;
        border-radius: 10px;
        margin-bottom: 2rem;
        color: white;
        text-align: center;
    }
    
    .main-header h1 {
        margin: 0;
        font-size: 2.5rem;
        font-weight: 700;
    }
    
    .main-header p {
        margin: 0.5rem 0 0 0;
        opacity: 0.9;
    }
    
    /* Card styling */
    .prediction-card {
        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
        border-radius: 20px;
        padding: 2rem;
        color: white;
        text-align: center;
        box-shadow: 0 10px 30px rgba(0,0,0,0.2);
        margin: 1rem 0;
    }
    
    .prediction-number {
        font-size: 5rem;
        font-weight: 800;
        margin: 1rem 0;
        line-height: 1;
    }
    
    .prediction-label {
        font-size: 1rem;
        text-transform: uppercase;
        letter-spacing: 2px;
        opacity: 0.9;
    }
    
    .stay-category {
        font-size: 1.2rem;
        font-weight: 600;
        margin-top: 1rem;
        padding: 0.5rem;
        border-radius: 10px;
        background: rgba(255,255,255,0.2);
    }
    
    /* Section headers */
    .section-header {
        font-size: 1.2rem;
        font-weight: 600;
        color: #667eea;
        margin: 1rem 0 1rem 0;
        padding-bottom: 0.5rem;
        border-bottom: 2px solid #667eea;
    }
    
    /* Info boxes */
    .info-box {
        background: #f8f9fa;
        border-left: 4px solid #667eea;
        padding: 1rem;
        border-radius: 8px;
        margin: 1rem 0;
    }
    
    /* Risk factor chips */
    .risk-chip {
        display: inline-block;
        background: #ff6b6b;
        color: white;
        padding: 0.3rem 0.8rem;
        border-radius: 20px;
        margin: 0.2rem;
        font-size: 0.85rem;
        font-weight: 500;
    }
    
    /* Button styling */
    .stButton > button {
        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
        color: white;
        border: none;
        padding: 0.75rem 1.5rem;
        font-weight: 600;
        width: 100%;
        transition: all 0.3s ease;
    }
    
    .stButton > button:hover {
        transform: translateY(-2px);
        box-shadow: 0 5px 15px rgba(102,126,234,0.4);
    }
</style>
""", unsafe_allow_html=True)

# ── Model loader with column extraction ────────────────────────────────────────
@st.cache_resource
def load_model_and_features():
    """Load the CatBoost model and extract expected features"""
    try:
        from catboost import CatBoostRegressor
        model = CatBoostRegressor()
        model.load_model('Catboost_Model_LOS.pkl')
        
        # Try to get expected feature names
        expected_features = None
        try:
            if hasattr(model, 'feature_names_'):
                expected_features = model.feature_names_
            elif hasattr(model, 'get_feature_names'):
                expected_features = model.get_feature_names()
        except:
            pass
            
        return model, expected_features
    except:
        try:
            import joblib
            model = joblib.load('Catboost_Model_LOS.pkl')
            return model, None
        except:
            try:
                with open('Catboost_Model_LOS.pkl', 'rb') as f:
                    model = pickle.load(f)
                return model, None
            except:
                st.error("❌ Failed to load model. Please check if 'Catboost_Model_LOS.pkl' exists.")
                return None, None

# ── Helper functions ───────────────────────────────────────────────────────────
def predict_los(model, input_data, expected_features=None):
    """Make prediction and return with interpretation"""
    try:
        # Ensure all expected columns are present
        if expected_features:
            # Check which expected features are missing
            missing_cols = set(expected_features) - set(input_data.columns)
            if missing_cols:
                st.warning(f"Adding missing columns with default values: {missing_cols}")
                for col in missing_cols:
                    input_data[col] = 0
            
            # Reorder columns to match model expectations
            input_data = input_data[expected_features]
        
        prediction = model.predict(input_data)[0]
        # Round to nearest whole number for days
        los = max(0, round(float(prediction)))  # Removed decimal, now whole number
        
        # Categorize LOS
        if los <= 3:
            category = "Short Stay"
            description = "Routine admission, expected quick recovery"
            icon = "🟢"
        elif los <= 7:
            category = "Moderate Stay"
            description = "Standard inpatient care duration"
            icon = "🟡"
        elif los <= 14:
            category = "Extended Stay"
            description = "Complex condition requiring longer monitoring"
            icon = "🟠"
        else:
            category = "Prolonged Stay"
            description = "Severe condition requiring intensive care"
            icon = "🔴"
        
        return los, category, description, icon
    except Exception as e:
        st.error(f"Prediction error: {str(e)}")
        st.info("💡 Tip: Check if all required fields are filled correctly")
        return None, None, None, None

def get_risk_factors(data):
    """Extract and return active risk factors"""
    risk_mapping = {
        'dialysisrenalendstage': 'Dialysis/Renal Failure',
        'asthma': 'Asthma',
        'irondef': 'Iron Deficiency',
        'pneum': 'Pneumonia',
        'substancedependence': 'Substance Dependence',
        'psychologicaldisordermajor': 'Major Psychiatric Disorder',
        'depress': 'Depression',
        'psychother': 'Other Psychiatric Disorder',
        'fibrosisandother': 'Fibrosis/Pulmonary Disease',
        'malnutrition': 'Malnutrition'
    }
    
    active_risks = []
    for key, label in risk_mapping.items():
        if key in data and data[key] == 1:
            active_risks.append(label)
    
    return active_risks

# ── Main app ───────────────────────────────────────────────────────────────────
def main():
    # Header
    st.markdown("""
    <div class="main-header">
        <h1>🏥 Hospital Length of Stay Predictor</h1>
        <p>AI-powered prediction using CatBoost regression model</p>
    </div>
    """, unsafe_allow_html=True)
    
    # Load model
    with st.spinner("Loading AI model..."):
        model, expected_features = load_model_and_features()
    
    if model is None:
        st.stop()
    
    # Display expected features if available (for debugging)
    if expected_features and st.sidebar.checkbox("Show Model Info", value=False):
        with st.sidebar.expander("📊 Model Features"):
            st.write(f"Expected {len(expected_features)} features:")
            st.write(expected_features)
    
    # ── SIDEBAR ────────────────────────────────────────────────────────────────
    with st.sidebar:
        st.markdown("## 🏥 Patient Information")
        st.markdown("---")
        
        # Demographics Section
        st.markdown("### 👤 Demographics")
        gender = st.selectbox("Gender", ["F", "M"], help="Patient's biological sex")
        
        rcount = st.selectbox(
            "Readmission Count (last 180 days)",
            ["0", "1", "2", "3", "4", "5+"],
            help="Number of prior hospital readmissions"
        )
        
        # BMI Input
        st.markdown("### 📏 Body Metrics")
        col1, col2 = st.columns(2)
        with col1:
            height_ft = st.number_input("Height (feet)", min_value=0.0, max_value=None, value=5.5, step=0.1, help="Height in feet")
        with col2:
            height_in = st.number_input("Height (inches)", min_value=0, max_value=None, value=0, step=1, help="Additional inches")
        
        weight_lbs = st.number_input("Weight (lbs)", min_value=0.0, max_value=None, value=150.0, step=1.0, help="Weight in pounds")
        
        # Calculate BMI
        height_total_inches = (height_ft * 12) + height_in
        if height_total_inches > 0:
            bmi = (weight_lbs / (height_total_inches ** 2)) * 703
            bmi = round(bmi, 1)
        else:
            bmi = 0.0
        
        # BMI Status (only show if valid)
        if bmi > 0:
            if bmi < 18.5:
                bmi_status = "⚠️ Underweight"
            elif bmi < 25:
                bmi_status = "✅ Normal"
            elif bmi < 30:
                bmi_status = "⚠️ Overweight"
            else:
                bmi_status = "⚠️ Obese"
            st.info(f"📊 BMI: **{bmi}** ({bmi_status})")
        else:
            st.info(f"📊 BMI: **{bmi}** (Invalid height/weight)")
        
        st.markdown("---")
        
        # Lab Results Section - NO RESTRICTIONS
        st.markdown("### 🧪 Lab Results")
        col1, col2 = st.columns(2)
        with col1:
            hematocrit = st.number_input("Hematocrit (%)", value=36.0, step=0.5, help="Red blood cell volume percentage")
            sodium = st.number_input("Sodium (mEq/L)", value=138.0, step=0.5, help="Serum sodium level")
            glucose = st.number_input("Glucose (mg/dL)", value=110.0, step=1.0, help="Blood glucose level")
            creatinine = st.number_input("Creatinine (mg/dL)", value=1.0, step=0.05, help="Kidney function marker")
        
        with col2:
            neutrophils = st.number_input("Neutrophils (×10³/µL)", value=6.0, step=0.1, help="White blood cell subtype")
            bloodureanitro = st.number_input("BUN (mg/dL)", value=18.0, step=0.5, help="Blood urea nitrogen level")
            hemo = st.number_input("Hemoglobin (g/dL)", value=12.5, step=0.1, help="Oxygen-carrying protein")
        
        st.markdown("---")
        
        # Vital Signs - NO RESTRICTIONS
        st.markdown("### 💓 Vital Signs")
        col1, col2 = st.columns(2)
        with col1:
            pulse = st.number_input("Heart Rate (bpm)", value=80, step=1, help="Beats per minute")
        with col2:
            respiration = st.number_input("Respiration Rate", value=16.0, step=0.5, help="Breaths per minute")
        
        st.markdown("---")
        
        # Comorbidities Section
        st.markdown("### 🩺 Comorbidities")
        st.caption("Select 1 if present, 0 if absent")
        
        col1, col2 = st.columns(2)
        with col1:
            dialysis = st.selectbox("Dialysis/Renal", [0, 1], format_func=lambda x: "✓ Present" if x else "✗ Absent")
            asthma = st.selectbox("Asthma", [0, 1], format_func=lambda x: "✓ Present" if x else "✗ Absent")
            irondef = st.selectbox("Iron Deficiency", [0, 1], format_func=lambda x: "✓ Present" if x else "✗ Absent")
            pneum = st.selectbox("Pneumonia", [0, 1], format_func=lambda x: "✓ Present" if x else "✗ Absent")
            substance = st.selectbox("Substance Dependence", [0, 1], format_func=lambda x: "✓ Present" if x else "✗ Absent")
        
        with col2:
            psychmajor = st.selectbox("Major Psychiatric", [0, 1], format_func=lambda x: "✓ Present" if x else "✗ Absent")
            depress = st.selectbox("Depression", [0, 1], format_func=lambda x: "✓ Present" if x else "✗ Absent")
            psychother = st.selectbox("Other Psychiatric", [0, 1], format_func=lambda x: "✓ Present" if x else "✗ Absent")
            fibrosis = st.selectbox("Fibrosis/Pulmonary", [0, 1], format_func=lambda x: "✓ Present" if x else "✗ Absent")
            malnutrition = st.selectbox("Malnutrition", [0, 1], format_func=lambda x: "✓ Present" if x else "✗ Absent")
        
        st.markdown("---")
        
        # Predict Button
        predict_button = st.button("🔮 PREDICT LENGTH OF STAY", type="primary", use_container_width=True)
    
    # ── MAIN CONTENT AREA ──────────────────────────────────────────────────────
    # Create two columns for main content
    col1, col2 = st.columns([1, 1])
    
    with col1:
        st.markdown('<div class="section-header">📋 Patient Summary</div>', unsafe_allow_html=True)
        
        # Create summary dataframe
        rcount_display = rcount
        
        # Format BMI display
        bmi_display = f"{bmi}" if bmi > 0 else "Invalid"
        if bmi > 0:
            bmi_display = f"{bmi} ({bmi_status})"
        
        summary_data = {
            "Category": ["Demographics", "Demographics", "Demographics",
                        "Labs", "Labs", "Labs", "Labs", "Labs", "Labs", "Labs",
                        "Vitals", "Vitals",
                        "Comorbidities", "Comorbidities", "Comorbidities", 
                        "Comorbidities", "Comorbidities", "Comorbidities", 
                        "Comorbidities", "Comorbidities", "Comorbidities", "Comorbidities"],
            "Parameter": ["Gender", "Readmission Count", "BMI",
                         "Hematocrit", "Neutrophils", "Sodium", "Glucose", 
                         "BUN", "Creatinine", "Hemoglobin",
                         "Heart Rate", "Respiration",
                         "Dialysis/Renal", "Asthma", "Iron Deficiency", "Pneumonia",
                         "Substance Dependence", "Major Psychiatric", "Depression",
                         "Other Psychiatric", "Fibrosis", "Malnutrition"],
            "Value": [gender, rcount_display, bmi_display,
                     f"{hematocrit:.1f} %", f"{neutrophils:.1f} ×10³/µL", 
                     f"{sodium:.1f} mEq/L", f"{glucose:.1f} mg/dL",
                     f"{bloodureanitro:.1f} mg/dL", f"{creatinine:.2f} mg/dL",
                     f"{hemo:.1f} g/dL",
                     f"{pulse} bpm", f"{respiration:.1f} /min",
                     "✓" if dialysis else "✗", "✓" if asthma else "✗",
                     "✓" if irondef else "✗", "✓" if pneum else "✗",
                     "✓" if substance else "✗", "✓" if psychmajor else "✗",
                     "✓" if depress else "✗", "✓" if psychother else "✗",
                     "✓" if fibrosis else "✗", "✓" if malnutrition else "✗"]
        }
        
        df_summary = pd.DataFrame(summary_data)
        st.dataframe(df_summary, use_container_width=True, hide_index=True, height=550)
    
    with col2:
        st.markdown('<div class="section-header">🎯 Prediction Results</div>', unsafe_allow_html=True)
        
        if predict_button:
            # Prepare input data for model
            rcount_num = int(rcount.replace('5+', '5'))
            
            input_dict = {
                "rcount": rcount_num,
                "gender": gender,
                "bmi": bmi if bmi > 0 else 25.0,  # Use default if BMI invalid
                "dialysisrenalendstage": dialysis,
                "asthma": asthma,
                "irondef": irondef,
                "pneum": pneum,
                "substancedependence": substance,
                "psychologicaldisordermajor": psychmajor,
                "depress": depress,
                "psychother": psychother,
                "fibrosisandother": fibrosis,
                "malnutrition": malnutrition,
                "hemo": hemo,
                "hematocrit": hematocrit,
                "neutrophils": neutrophils,
                "sodium": sodium,
                "glucose": glucose,
                "bloodureanitro": bloodureanitro,
                "creatinine": creatinine,
                "pulse": pulse,
                "respiration": respiration
            }
            
            input_df = pd.DataFrame([input_dict])
            
            # Make prediction
            los, category, description, icon = predict_los(model, input_df, expected_features)
            
            if los is not None:
                # Display prediction card with whole number
                st.markdown(f"""
                <div class="prediction-card">
                    <div class="prediction-label">PREDICTED LENGTH OF STAY</div>
                    <div class="prediction-number">{los}</div>
                    <div style="font-size: 1.2rem; margin-top: -0.5rem;">days</div>
                    <div class="stay-category">
                        {icon} {category} {icon}
                    </div>
                    <div style="margin-top: 1rem; font-size: 0.9rem;">
                        {description}
                    </div>
                </div>
                """, unsafe_allow_html=True)
                
                # Risk factors
                active_risks = get_risk_factors(input_dict)
                if active_risks:
                    st.markdown("#### ⚠️ Active Risk Factors")
                    risk_chips = "".join(f'<span class="risk-chip">{risk}</span>' for risk in active_risks)
                    st.markdown(risk_chips, unsafe_allow_html=True)
                    
                    risk_count = len(active_risks)
                    if risk_count >= 3:
                        st.warning(f"⚠️ {risk_count} comorbidities detected. Consider enhanced care coordination.")
                
                # BMI insights (only if valid)
                if bmi > 0:
                    if bmi < 18.5:
                        st.warning("📉 Underweight BMI - Monitor nutritional status")
                    elif bmi > 30:
                        st.warning("📈 Obese BMI - Consider weight management and associated risks")
                    elif bmi > 25:
                        st.info("📊 Overweight BMI - Monitor for metabolic complications")
                
                # Clinical recommendations based on LOS
                st.markdown("#### 💡 Clinical Insights")
                if los <= 3:
                    st.info("""
                    **Recommendations:**
                    - Routine discharge planning
                    - Standard post-discharge follow-up
                    - Monitor for early readmission risk factors
                    """)
                elif los <= 7:
                    st.info("""
                    **Recommendations:**
                    - Coordinate with case management
                    - Ensure discharge criteria are met
                    - Schedule follow-up within 7 days
                    """)
                elif los <= 14:
                    st.warning("""
                    **Recommendations:**
                    - Involve multidisciplinary team
                    - Consider rehabilitation services
                    - Detailed discharge planning required
                    """)
                else:
                    st.error("""
                    **Recommendations:**
                    - Intensive case management needed
                    - Consider skilled nursing facility
                    - Complex care coordination required
                    - Regular team meetings recommended
                    """)
                
                # Visual indicator
                st.markdown("#### 📊 Stay Duration Indicator")
                progress_value = min(los / 21, 1.0)
                st.progress(progress_value, text=f"Stay duration: {los} days")
                
        else:
            st.info("👈 **Ready for prediction**\n\nFill in all patient information in the sidebar and click 'Predict Length of Stay' to see results.")
            
            # Show example or demo message
            st.markdown("""
            <div class="info-box">
                <strong>📌 How to use:</strong><br>
                1. Enter patient demographics including height/weight for BMI<br>
                2. Input lab results and vital signs (any values allowed)<br>
                3. Select comorbidities (1 = present, 0 = absent)<br>
                4. Click the predict button to see results<br>
                5. Review risk factors and clinical insights
            </div>
            """, unsafe_allow_html=True)
            
            # Display model information
            with st.expander("ℹ️ About the Model"):
                st.markdown("""
                **Model Details:**
                - **Algorithm:** CatBoost Regressor
                - **Features:** 22 clinical parameters
                - **Target:** Length of Stay (days)
                - **Training Data:** Historical hospital admissions
                
                **Key Features:**
                - Demographics (gender, BMI, readmission count)
                - Lab values (CBC, metabolic panel)
                - Vital signs (heart rate, respiration)
                - Comorbidities (10 conditions)
                
                **BMI Categories:**
                - Underweight: < 18.5
                - Normal: 18.5 - 24.9
                - Overweight: 25 - 29.9
                - Obese: ≥ 30
                
                **Output Format:**
                - Predicted length of stay is rounded to the nearest whole day
                - Categories help interpret the expected care intensity
                
                **Note:** Lab values and vital signs can accept any numeric value with no restrictions.
                """)
    
    # Footer disclaimer
    st.markdown("---")
    st.markdown("""
    <div style="background: #fff3e0; padding: 1rem; border-radius: 8px; margin-top: 1rem;">
        <small>
        ⚠️ <strong>Clinical Disclaimer:</strong> This tool is for informational and research purposes only. 
        Predictions are based on statistical models and should not replace clinical judgment. 
        Always consult with qualified healthcare professionals for medical decisions.
        </small>
    </div>
    """, unsafe_allow_html=True)

if __name__ == "__main__":
    main()

Overwriting app.py